/**
 * AppDelegate+BackgroundUpload.swift
 *
 * Extension to handle background URLSession events.
 *
 * When iOS completes background URL session transfers, it relaunches the
 * app (if needed) and calls application(_:handleEventsForBackgroundURLSession:completionHandler:).
 *
 * We must:
 *   1. Reconnect to our background URLSession
 *   2. Hold the completionHandler
 *   3. Let URLSession delegate callbacks fire (completion, error, progress)
 *   4. Call the completionHandler when all events are delivered
 *
 * In Expo SDK 55, the AppDelegate is generated by prebuild. This file is
 * injected via the config plugin and swizzled into the app delegate.
 */

import Foundation
import UIKit
import ExpoModulesCore

// MARK: - Protocol for AppDelegate injection

@objc protocol BackgroundUploadAppDelegate {
  func handleBackgroundUploadEvents(
    identifier: String,
    completionHandler: @escaping () -> Void
  )
}

// MARK: - Swizzled AppDelegate methods

extension ExpoAppDelegate {
  /**
   * Intercept handleEventsForBackgroundURLSession and forward to our handler.
   *
   * In Expo SDK 55, ExpoAppDelegate handles the standard AppDelegate methods.
   * We use method swizzling to add background URL session handling.
   */
  @objc func backgroundUpload_handleEventsForBackgroundURLSession(
    _ application: UIApplication,
    identifier: String,
    completionHandler: @escaping () -> Void
  ) {
    // Forward to BackgroundUploadHandler
    BackgroundUploadHandler.shared.handleEventsForBackgroundURLSession(
      identifier: identifier,
      completionHandler: completionHandler
    )
  }
}

// MARK: - Manual registration via AppDelegate

/**
 * Call this from AppDelegate.application(_:didFinishLaunchingWithOptions:) or
 * the equivalent Expo setup point.
 *
 * The config plugin injects a call to:
 *   BackgroundUploadManager.shared.register()
 *
 * This sets up swizzling to intercept background URL session events.
 */
class BackgroundUploadManager {

  static let shared = BackgroundUploadManager()

  private var isRegistered = false

  func register() {
    guard !isRegistered else { return }
    isRegistered = true

    // Pre-create the background session so iOS can reconnect to it
    // after app termination + relaunch for background events.
    _ = BackgroundUploadHandler.shared.getBackgroundSession()

    // Register for app lifecycle notifications
    NotificationCenter.default.addObserver(
      self,
      selector: #selector(appDidEnterBackground),
      name: UIApplication.didEnterBackgroundNotification,
      object: nil
    )

    // Try to swizzle handleEventsForBackgroundURLSession
    swizzleAppDelegate()
  }

  @objc private func appDidEnterBackground() {
    // App is entering background — background upload tasks are now managed by iOS.
    // The URLSession will continue uploading even if JS is suspended.
  }

  private func swizzleAppDelegate() {
    guard let appDelegate = UIApplication.shared.delegate else { return }
    let appDelegateClass: AnyClass = type(of: appDelegate)

    // Swizzle application(_:handleEventsForBackgroundURLSession:completionHandler:)
    let originalSelector = #selector(UIApplicationDelegate.application(_:handleEventsForBackgroundURLSession:completionHandler:))
    let swizzledSelector = #selector(ExpoAppDelegate.backgroundUpload_handleEventsForBackgroundURLSession(_:identifier:completionHandler:))

    guard let originalMethod = class_getInstanceMethod(appDelegateClass, originalSelector),
          let swizzledMethod = class_getInstanceMethod(ExpoAppDelegate.self, swizzledSelector) else {
      // Method doesn't exist yet — add it
      class_addMethod(appDelegateClass, originalSelector, method_getImplementation(swizzledMethod), method_getTypeEncoding(swizzledMethod))
      return
    }

    // Swap implementations
    let didAddMethod = class_addMethod(
      appDelegateClass, originalSelector,
      method_getImplementation(swizzledMethod),
      method_getTypeEncoding(swizzledMethod)
    )
    if didAddMethod {
      class_replaceMethod(appDelegateClass, swizzledSelector,
                          method_getImplementation(originalMethod),
                          method_getTypeEncoding(originalMethod))
    } else {
      method_exchangeImplementations(originalMethod, swizzledMethod)
    }
  }
}
