// IOSSecurityModule.m
// Objective-C bridging file — exposes Swift class to the React Native runtime.
// This file is required because RCT_EXTERN_MODULE links the ObjC bridge
// to the Swift implementation. Generated by withSecurityModule config plugin.

// React headers are imported via #import (NOT @import React).
//
// WHY #import, not @import:
//   RCT_EXTERN_MODULE and RCT_EXTERN_METHOD are C preprocessor macros defined in
//   RCTBridgeModule.h. Clang modules do NOT propagate #define macros to importing
//   translation units — @import loads the module but macros stay invisible.
//   #import <React/RCTBridgeModule.h> is textual inclusion; macros are visible.
//
// WHY #import resolves in the app target:
//   CocoaPods sets FRAMEWORK_SEARCH_PATHS on the app target xcconfig to include
//   React.xcframework. <React/X.h> resolves as a framework header import via that
//   path without needing HEADER_SEARCH_PATHS.
#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>

// RCT_EXTERN_MODULE usage: the macro MUST be prefixed with @interface and the
// entire declaration (module + all methods) must be closed with @end.
//
// RCT_EXTERN_REMAP_MODULE (what RCT_EXTERN_MODULE expands to) produces:
//   objc_name: objc_supername @ end @interface objc_name(RCTExternModule)...
// This fragment is only syntactically valid when preceded by "@interface ".
// Using RCT_EXTERN_MODULE without @interface leaves the "objc_name:" fragment
// as an orphaned label → "type specifier missing, defaults to int" on that line,
// then "missing context for method declaration" on every RCT_EXTERN_METHOD line.
//
// Correct pattern (from RCTBridgeModule.h line 284):
//   @interface RCT_EXTERN_MODULE(ClassName, SuperClass)
//   RCT_EXTERN_METHOD(methodSignature)
//   @end
@interface RCT_EXTERN_MODULE(IOSSecurityModule, RCTEventEmitter)

RCT_EXTERN_METHOD(getSecurityFlags:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(isJailbreakDetected:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(isDebuggerAttached:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(isScreenBeingRecorded:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(isVPNDetected:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(isProxyDetected:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(isDylibInjectionDetected:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(isBundleTampered:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(generateAppAttestKey:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(attestAppAttestKey:(NSString *)keyId
                  clientDataHash:(NSString *)clientDataHash
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(generateAppAttestAssertion:(NSString *)keyId
                  challenge:(NSString *)challenge
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(generateDeviceCheckToken:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

@end
