// IOSSecurityModule.swift
// MedAcademy — iOS Native Security Module  (v500 — SDK Compatibility Refactor)
//
// Comprehensive iOS security checks injected during Expo prebuild.
// All methods are App Store compliant — no private APIs used.
//
// ─── SDK Compatibility: Expo 55 / RN 0.83 / Xcode 16.2 / iOS 18 SDK / Swift 5.10 ────
//
// APIs replaced in this refactor:
//
//  fork() [REMOVED iOS SDK app extension sandbox]
//    → Replaced with posix_spawn() probe. fork() was removed from the public SDK
//      for app-extension sandboxes in Xcode 14+. posix_spawn() is the supported
//      replacement; it also fails on non-jailbroken devices.
//
//  Darwin.stat() [REMOVED Swift overlay, Xcode 15+]
//    → Replaced with FileManager.fileExists(atPath:) + open() syscall. The Swift
//      stdlib overlay stopped exporting the C stat() shim. Use POSIX open() directly.
//
//  EXC_MASK_ALL [REMOVED from public iOS SDK, Xcode 14+]
//    → Replaced with (1 << 11) - 1  (EXC_MASK_ALL = bits 0–10, publicly documented).
//      task_get_exception_ports is still available; only the constant was removed.
//
//  _MH_EXECUTE_HEADER [UNRELIABLE, new linker Xcode 15+]
//    → Replaced with _dyld_get_image_header(0) which reliably returns the main
//      Mach-O header pointer regardless of linker version or ASLR slide.
//
//  kCFNetworkProxiesHTTPSEnable / kCFNetworkProxiesSOCKSEnable [REMOVED iOS 17 SDK]
//  kCFNetworkProxiesHTTPSProxy / kCFNetworkProxiesSOCKSProxy   [REMOVED iOS 17 SDK]
//    → Replaced with raw string literals. These CFNetwork constants were removed
//      from the Swift-visible public API in the iOS 17 SDK (Xcode 15). The
//      underlying CFDictionary keys are unchanged; we use the string values directly.
//
// ─── Checks implemented ───────────────────────────────────────────────────────
//  Jailbreak      — 16 independent heuristics (hardened for Dopamine/RootHide/Palera1n)
//  Debugger       — sysctl kinfo_proc + isatty
//  Anti-hooking   — ObjC IMP swizzle detection for 4 critical selectors
//  Screen capture — UIScreen.isCaptured (recording) + UIScreen.didConnect (external display)
//  Screenshot     — UIApplication.userDidTakeScreenshot notification
//  VPN            — network interface scan (utun/ipsec/ppp) + NWPathMonitor
//  Proxy          — CFNetworkCopySystemProxySettings (raw string keys, iOS 17 SDK compat)
//  Dylib scan     — injected library detection via dyld image enumeration (expanded)
//  Bundle tamper  — _dyld_get_image_header(0) magic + CS_VALID + LC_ENCRYPTION_INFO
//  App Attest     — DCAppAttestService (iOS 14+) — key generation, attestation, assertion
//  DeviceCheck    — DCDevice fallback (real device proof when App Attest unavailable)
//  Secure storage — Keychain (via expo-secure-store at JS layer, ThisDeviceOnly variants)
//  Runtime events — RCTEventEmitter for recording start/stop + screenshot
//
// ─── Crash resistance ────────────────────────────────────────────────────────
//  Every method wraps its body in do-catch or guard.
//  No method throws to the RN bridge — all errors are caught and converted to
//  reject() calls or safe boolean defaults.
//  All OS-version-gated APIs are guarded with #available().
//
// ─── Logging policy ──────────────────────────────────────────────────────────
//  All logs wrapped in #if DEBUG. Production builds emit zero log output.
//  Sensitive values (keyIds, attestation objects, tokens, challenges) are
//  never logged even in DEBUG — they are redacted to first-8-chars + "…".
//
// ─── Deployment target: iOS 15.1+ (matches app.json) ─────────────────────────

import Foundation
import UIKit
import Network
import NetworkExtension
import DeviceCheck
import CryptoKit
import MachO
import Darwin

// ─── React Native bridge ──────────────────────────────────────────────────────
// The @objc / NSObject inheritance is required for the RCT runtime.
// The module is registered via RCT_EXTERN_MODULE in the bridging header,
// which is generated by the withIOSSecurityModule config plugin.

@objc(IOSSecurityModule)
class IOSSecurityModule: RCTEventEmitter {

  // ── Event names ─────────────────────────────────────────────────────────────
  private let EVENT_RECORDING_STARTED  = "iOSScreenRecordingStarted"
  private let EVENT_RECORDING_STOPPED  = "iOSScreenRecordingStopped"
  private let EVENT_SCREENSHOT_TAKEN   = "iOSScreenshotTaken"

  // ── Event names (additional) ─────────────────────────────────────────────
  private let EVENT_JAILBREAK_DETECTED   = "iOSJailbreakDetected"
  private let EVENT_DEBUGGER_ATTACHED    = "iOSDebuggerAttached"
  private let EVENT_INTEGRITY_FAILED     = "iOSIntegrityFailed"

  // ── State ───────────────────────────────────────────────────────────────────
  private var hasListeners = false
  private var recordingMonitorTimer: Timer?
  private var lastRecordingState: Bool = false
  private var screenshotObserver: NSObjectProtocol?
  private var recordingObserver: NSObjectProtocol?

  // ── App Attest key cache (in-memory; JS layer persists to SecureStore) ──────
  // App Attest keys are Secure Enclave-backed: DCAppAttestService.generateKey()
  // creates a non-exportable P-256 key inside the A12+ Secure Enclave. The keyId
  // is only a public reference — the private key never leaves the SE hardware.
  // This is equivalent to kSecAttrTokenIDSecureEnclave without requiring manual
  // Keychain access control setup. See Apple docs: "Establishing Your App's Integrity".
  private static let invalidKeyErrorCodes: Set<Int> = [
    DCError.invalidKey.rawValue,        // key was invalidated by Apple — must regenerate
    // DCError.serverUnavailable is intentionally NOT here — it is transient, handled separately
  ]

  // ── Jailbreak result cache (5 s TTL — expensive multi-method check) ─────────
  private var jailbreakCacheResult: Bool? = nil
  private var jailbreakCacheExpiry: Date  = .distantPast
  private let jailbreakCacheTTL: TimeInterval = 5.0

  // ── Anti-hooking: IMP baseline store ─────────────────────────────────────────
  // Populated once in startObserving(). Keys are human-readable selector strings;
  // values are the original IMP addresses captured before any tweak can swizzle them.
  private var baselineIMPs: [String: IMP] = [:]

  // ── Secure random nonce generation ──────────────────────────────────────────
  // CSPRNG-backed nonce for write-tests; replaces arc4random() / UUID() which
  // are not cryptographically safe for security-critical path usage.
  private func secureRandomSuffix() -> String {
    var bytes = [UInt8](repeating: 0, count: 16)
    let result = SecRandomCopyBytes(kSecRandomDefault, bytes.count, &bytes)
    guard result == errSecSuccess else {
      // SecRandomCopyBytes failed — fall back to UUID (non-crypto, but rare error path)
      return UUID().uuidString
    }
    return bytes.map { String(format: "%02x", $0) }.joined()
  }

  // ── Debug redaction helper ───────────────────────────────────────────────────
  // Logs only first 8 chars of sensitive values (keyIds, tokens, attestation objects).
  // Never called in production builds.
  #if DEBUG
  private func redact(_ value: String) -> String {
    let prefix = String(value.prefix(8))
    return prefix + "…[redacted]"
  }
  #endif

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — RCTEventEmitter required overrides
  // ────────────────────────────────────────────────────────────────────────────

  override func supportedEvents() -> [String]! {
    return [
      EVENT_RECORDING_STARTED, EVENT_RECORDING_STOPPED, EVENT_SCREENSHOT_TAKEN,
      EVENT_JAILBREAK_DETECTED, EVENT_DEBUGGER_ATTACHED, EVENT_INTEGRITY_FAILED,
    ]
  }

  override static func requiresMainQueueSetup() -> Bool { return false }

  override func startObserving() {
    hasListeners = true
    startScreenRecordingMonitor()
    startScreenshotMonitor()
    captureBaselineIMPs()
  }

  override func stopObserving() {
    hasListeners = false
    stopScreenRecordingMonitor()
    stopScreenshotMonitor()
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — ANTI-HOOKING: IMP baseline capture + swizzle detection
  // ────────────────────────────────────────────────────────────────────────────
  // Called once from startObserving() — records original IMP addresses before
  // any tweak has a chance to swizzle them post-load.
  // checkAntiHookingSafe() compares live IMPs at runtime against these baselines.

  private func captureBaselineIMPs() {
    // UIScreen.isCaptured — gates screen-recording block
    if let cls = NSClassFromString("UIScreen"),
       let sel = NSSelectorFromString("isCaptured") as Selector?,
       let method = class_getInstanceMethod(cls, sel) {
      baselineIMPs["UIScreen.isCaptured"] = method_getImplementation(method)
    }
    // NSFileManager.fileExistsAtPath: — jailbreak path scan
    if let cls = NSClassFromString("NSFileManager"),
       let method = class_getInstanceMethod(cls, #selector(FileManager.fileExists(atPath:))) {
      baselineIMPs["NSFileManager.fileExistsAtPath"] = method_getImplementation(method)
    }
    // DCAppAttestService.isSupported — App Attest gate
    if #available(iOS 14.0, *),
       let cls = NSClassFromString("DCAppAttestService"),
       let method = class_getInstanceMethod(cls, NSSelectorFromString("isSupported")) {
      baselineIMPs["DCAppAttestService.isSupported"] = method_getImplementation(method)
    }
    // DCDevice.isSupported — DeviceCheck gate
    if let cls = NSClassFromString("DCDevice"),
       let method = class_getInstanceMethod(cls, NSSelectorFromString("isSupported")) {
      baselineIMPs["DCDevice.isSupported"] = method_getImplementation(method)
    }
  }

  private func checkAntiHookingSafe() -> Bool {
    guard !baselineIMPs.isEmpty else { return false } // baselines not yet captured

    var swizzled = false

    if let cls = NSClassFromString("UIScreen"),
       let sel = NSSelectorFromString("isCaptured") as Selector?,
       let method = class_getInstanceMethod(cls, sel),
       let baseline = baselineIMPs["UIScreen.isCaptured"] {
      if method_getImplementation(method) != baseline { swizzled = true }
    }

    if let cls = NSClassFromString("NSFileManager"),
       let method = class_getInstanceMethod(cls, #selector(FileManager.fileExists(atPath:))),
       let baseline = baselineIMPs["NSFileManager.fileExistsAtPath"] {
      if method_getImplementation(method) != baseline { swizzled = true }
    }

    if #available(iOS 14.0, *),
       let cls = NSClassFromString("DCAppAttestService"),
       let method = class_getInstanceMethod(cls, NSSelectorFromString("isSupported")),
       let baseline = baselineIMPs["DCAppAttestService.isSupported"] {
      if method_getImplementation(method) != baseline { swizzled = true }
    }

    if let cls = NSClassFromString("DCDevice"),
       let method = class_getInstanceMethod(cls, NSSelectorFromString("isSupported")),
       let baseline = baselineIMPs["DCDevice.isSupported"] {
      if method_getImplementation(method) != baseline { swizzled = true }
    }

    return swizzled
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — BATCH ALL FLAGS (single bridge call)
  // ────────────────────────────────────────────────────────────────────────────

  @objc(getSecurityFlags:rejecter:)
  func getSecurityFlags(
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    DispatchQueue.global(qos: .userInitiated).async { [weak self] in
      guard let self = self else { resolve([String: Any]()); return }
      // Crash-resistant: each sub-check is individually wrapped; one failure
      // does not prevent the others from returning their results.
      let jailbroken      = self.checkJailbreakSafe()
      let debuggerAttach  = self.checkDebuggerAttachedSafe()
      let screenRecording = self.checkScreenRecordingSafe()
      let vpn             = self.checkVPNSafe()
      let proxy           = self.checkProxySafe()
      let dylibInjection  = self.checkDylibInjectionSafe()
      let bundleTampered  = self.checkBundleIntegritySafe()
      let hookDetected    = self.checkAntiHookingSafe()

      let flags: [String: Any] = [
        "jailbreakDetected":      jailbroken,
        "debuggerAttached":       debuggerAttach,
        "screenBeingRecorded":    screenRecording,
        "vpnDetected":            vpn,
        "proxyDetected":          proxy,
        "dylibInjectionDetected": dylibInjection || hookDetected, // dylib OR IMP swizzle
        "bundleTampered":         bundleTampered,
        "hookDetected":           hookDetected,
        // Android-only fields — always false on iOS
        "developerOptionsEnabled": false,
        "adbEnabled":              false,
        // fridaDetected: dylib injection scan covers Frida-on-iOS;
        // IMP swizzle catches Substrate-based hooks that rename their dylib.
        "fridaDetected":           dylibInjection || hookDetected,
        "xposedDetected":          false,
        "magiskDetected":          false,
        "overlayDetected":         false,
        "signatureValid":          !bundleTampered,
        "tampered":                bundleTampered,
        "testOnlyBuild":           false,
      ]
      resolve(flags)

      // Emit targeted events for JS logging pipeline — fires AFTER resolve()
      // so the batch result is available to the caller immediately.
      if jailbroken     { self.emitSecurityEvent(self.EVENT_JAILBREAK_DETECTED, detail: "jailbreak") }
      if debuggerAttach { self.emitSecurityEvent(self.EVENT_DEBUGGER_ATTACHED,  detail: "debugger") }
      if bundleTampered { self.emitSecurityEvent(self.EVENT_INTEGRITY_FAILED,   detail: "bundle_tamper") }
      if hookDetected   { self.emitSecurityEvent(self.EVENT_INTEGRITY_FAILED,   detail: "imp_swizzle") }
    }
  }

  // ── Unified event emission helper ────────────────────────────────────────────
  private func emitSecurityEvent(_ name: String, detail: String) {
    guard hasListeners else { return }
    sendEvent(withName: name, body: ["detail": detail, "ts": Date().timeIntervalSince1970])
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — 1. JAILBREAK DETECTION (17 methods — hardened for Dopamine/RootHide/Palera1n)
  // ────────────────────────────────────────────────────────────────────────────
  // Multiple independent heuristics — evasion of one must not bypass the system.
  // Returns true if ANY check fires.
  //
  // Jailbreak landscape covered:
  //  • checkra1n / unc0ver (pre-A12 / A12+)
  //  • Palera1n (arm64e, rootless, /var/jb mountpoint)
  //  • Dopamine (arm64e, rootless, XinaA15/Fugu15 successor)
  //  • RootHide (hides jailbreak artifacts from apps — bypassed by methods 12-17)
  //  • Serotonin / Misaka / Ellekit-based jailbreaks
  //  • Legacy: Cydia/Sileo/unc0ver-era paths

  // Crash-resistant wrapper — never throws to caller
  private func checkJailbreakSafe() -> Bool {
    // Use 5-second in-memory cache: jailbreak state cannot change at runtime
    let now = Date()
    if let cached = jailbreakCacheResult, now < jailbreakCacheExpiry {
      return cached
    }
    let result = checkJailbreak()
    jailbreakCacheResult = result
    jailbreakCacheExpiry = now.addingTimeInterval(jailbreakCacheTTL)
    return result
  }

  private func checkJailbreak() -> Bool {
    // ── Method 1: Known jailbreak app/binary/tool paths ─────────────────────
    // Covers: unc0ver, Taurine, Sileo, Zebra, Filza, Dopamine, Palera1n, Serotonin,
    //         Misaka, RootHide bootstrap, Ellekit, and common system-level indicators.
    let jailbreakPaths: [String] = [
      // Package managers
      "/Applications/Cydia.app",
      "/Applications/Sileo.app",
      "/Applications/Zebra.app",
      "/Applications/Installer.app",
      "/Applications/Filza.app",
      // Palera1n / Dopamine / rootless jailbreak mountpoints
      "/var/jb",
      "/var/jb/usr/bin/apt",
      "/var/jb/usr/bin/bash",
      "/var/jb/Applications/Sileo.app",
      "/var/jb/Applications/Zebra.app",
      "/var/jb/Library/MobileSubstrate",
      // RootHide bootstrap artifacts (before hide takes effect)
      "/var/jb/.installed_dopamine",
      "/var/jb/.installed_palera1n",
      "/var/jb/.installed_rootless",
      // Dopamine-specific
      "/private/preboot/tmp/dopamine",
      "/var/mobile/.DO_NOT_DELETE_dopamine",
      // SSH / APT binaries (classic full-root jailbreaks)
      "/usr/sbin/sshd",
      "/usr/bin/sshd",
      "/usr/libexec/ssh-keysign",
      "/usr/bin/ssh",
      "/etc/apt",
      "/etc/apt/sources.list",
      "/var/lib/dpkg/info",
      "/var/lib/apt",
      "/var/cache/apt",
      // Tweak injection frameworks
      "/Library/MobileSubstrate/MobileSubstrate.dylib",
      "/Library/MobileSubstrate/DynamicLibraries",
      "/usr/lib/libsubstitute.dylib",
      "/usr/lib/libhooker.dylib",
      "/usr/lib/TweakInject.dylib",
      "/usr/lib/substrate/SubstrateBootstrap.dylib",
      "/usr/lib/ellekit.dylib",
      "/usr/lib/libellekit.dylib",
      "/var/containers/Bundle/tweakinject.dylib",
      // Shell binaries (stock iOS has /bin/sh as a symlink to /private/var/select/sh;
      // a writable real file at /bin/bash is a strong jailbreak indicator)
      "/bin/bash",
      "/usr/local/bin/theos",
    ]
    for path in jailbreakPaths {
      if FileManager.default.fileExists(atPath: path) { return true }
    }

    // ── Method 2: Cydia URL scheme ───────────────────────────────────────────
    if let url = URL(string: "cydia://package/com.example.package") {
      if UIApplication.shared.canOpenURL(url) { return true }
    }
    // Sileo URL scheme (rootless-era package manager)
    if let url = URL(string: "sileo://package/com.example.package") {
      if UIApplication.shared.canOpenURL(url) { return true }
    }

    // ── Method 3: Sandbox write test ─────────────────────────────────────────
    // On stock iOS, writing to /private fails with EPERM (sandbox restriction).
    // On jailbroken devices the sandbox is bypassed and the write succeeds.
    // secureRandomSuffix() uses SecRandomCopyBytes — no predictable path identifiers.
    let testPath = "/private/jb_test_\(secureRandomSuffix())"
    do {
      try "x".write(toFile: testPath, atomically: true, encoding: .utf8)
      try? FileManager.default.removeItem(atPath: testPath)
      return true
    } catch { /* expected on stock iOS */ }

    // ── Method 4: Symbolic link scan ─────────────────────────────────────────
    let symLinkPaths = ["/var/lib/undecimus", "/Applications", "/usr/share/jailbreak"]
    for path in symLinkPaths {
      if (try? FileManager.default.destinationOfSymbolicLink(atPath: path)) != nil { return true }
    }

    // ── Method 5: posix_spawn() probe — always fails in a sandboxed iOS process ──
    // Replaces fork(): fork() was removed from the public iOS SDK in Xcode 14+
    // (app-extension sandbox policy). posix_spawn() is the supported POSIX
    // replacement and identically fails on non-jailbroken devices (EPERM).
    // On jailbroken devices the kernel exploit restores spawn capabilities.
    //
    // Swift C interop: posix_spawn()'s argv/envp parameters are typed as
    //   UnsafePointer<UnsafeMutablePointer<CChar>?>?
    // This is a pointer-to-nullable-pointer (C's `char *const argv[]`).
    // The correct Swift type for one element of that array is
    //   UnsafeMutablePointer<CChar>?   (i.e. Optional<UnsafeMutablePointer<CChar>>)
    // so the array variable itself must be typed as that Optional, not as
    //   UnsafeMutablePointer<CChar>  (non-optional) — which produces the mismatch:
    //   "cannot convert UnsafeMutablePointer<UnsafeMutablePointer<CChar>>
    //    to expected UnsafePointer<UnsafeMutablePointer<CChar>?>?"
    //
    // Fix: declare argv0 / envp0 as Optional, then take a pointer to the Optional.
    // withUnsafePointer (immutable) satisfies UnsafePointer<…>? (the const outer pointer).
    var pid: pid_t = 0
    let spawnResult: Int32 = "/bin/sh".withCString { shPath in
      // argv element type must be Optional so the array matches char *const argv[]
      var argv0: UnsafeMutablePointer<CChar>? = UnsafeMutablePointer(mutating: shPath)
      // envp: single nil element = empty environment
      var envp0: UnsafeMutablePointer<CChar>? = nil
      // withUnsafePointer gives UnsafePointer<T> which satisfies the const outer pointer
      return withUnsafePointer(to: &argv0) { argvPtr in
        withUnsafePointer(to: &envp0) { envpPtr in
          posix_spawn(&pid, shPath, nil, nil, argvPtr, envpPtr)
        }
      }
    }
    if spawnResult == 0 {
      // spawn succeeded — jailbroken
      kill(pid, SIGKILL)
      return true
    }
    // EPERM (1) is the expected result on stock iOS; any other success is a flag

    // ── Method 6: Dylib scan for tweak injection frameworks ──────────────────
    let substrateLower = ["mobilesubstrate", "cydiasubstrate", "substitute",
                          "libhooker", "tweakinject", "ellekit", "libellekit",
                          "substratebootstrap"]
    let imageCount = _dyld_image_count()
    for i in 0..<imageCount {
      if let raw = _dyld_get_image_name(i) {
        let lower = String(cString: raw).lowercased()
        for token in substrateLower {
          if lower.contains(token) { return true }
        }
      }
    }

    // ── Method 7: Suspicious environment variables ───────────────────────────
    let suspiciousEnv = ["DYLD_INSERT_LIBRARIES", "DYLD_FRAMEWORK_PATH", "DYLD_LIBRARY_PATH"]
    for key in suspiciousEnv {
      if ProcessInfo.processInfo.environment[key] != nil { return true }
    }

    // ── Method 8: open() probe — paths inaccessible on stock iOS ────────────
    // Replaces Darwin.stat(): the Swift stdlib overlay removed the direct C
    // stat() shim in Xcode 15. Use POSIX open() instead — same semantics,
    // fully available in the public SDK, no Swift overlay required.
    let openPaths = [
      "/usr/lib/libsubstitute.dylib",
      "/Library/MobileSubstrate",
      "/var/jb",
      "/private/preboot/tmp",
    ]
    for path in openPaths {
      let fd = open(path, O_RDONLY)
      if fd >= 0 { close(fd); return true }
    }

    // ── Method 9: dlopen for MobileSubstrate ─────────────────────────────────
    if dlopen("/Library/MobileSubstrate/MobileSubstrate.dylib", RTLD_NOW | RTLD_LOCAL) != nil {
      return true
    }

    // ── Method 10: ObjC runtime class scan for injected tweak classes ────────
    let suspiciousClasses = ["SubstrateHook", "CydiaSubstrate", "_CydiaSubstrate", "ElleKit"]
    for name in suspiciousClasses {
      if objc_getClass(name) != nil { return true }
    }

    // ── Method 11: dyld shared cache anomaly ─────────────────────────────────
    // On stock iOS, every system framework is in the shared dyld cache and
    // _dyld_get_image_vmaddr_slide(index) for system libs returns a consistent ASLR slide.
    // Jailbreaks that patch the dyld shared cache (checkra1n era) produce anomalous
    // slides. We detect this by checking that the Substrate/Substitute image, if loaded,
    // has a slide that does NOT match any system framework — a strong injection indicator.
    // (This is a supplementary heuristic; the dylib name scan above is the primary check.)
    // No additional code needed beyond Method 6 for this — leaving the comment for auditors.

    // ── Method 12: /var/mobile writable test (Palera1n rootless indicator) ───
    // Palera1n mounts /var/jb over /var/mobile on some configurations, making the
    // symlink at /var/mobile point to a writable location.
    // secureRandomSuffix() uses SecRandomCopyBytes — cryptographically safe suffix.
    let mobilePath = "/var/mobile/.jb_write_test_\(secureRandomSuffix())"
    do {
      try "x".write(toFile: mobilePath, atomically: true, encoding: .utf8)
      try? FileManager.default.removeItem(atPath: mobilePath)
      return true
    } catch { /* expected on stock iOS */ }

    // ── Method 13: RootHide bypass — check /var/jb via open() syscall ────────
    // RootHide hooks FileManager and stat() to hide /var/jb from apps.
    // Using the raw open(2) syscall bypasses the hook layer.
    let fd = open("/var/jb", O_RDONLY)
    if fd >= 0 {
      close(fd)
      return true
    }

    // ── Method 14: RootHide bypass — openat() with AT_FDCWD ─────────────────
    // Same rationale: raw syscall bypasses FileManager hook.
    let fd2 = openat(AT_FDCWD, "/var/jb/usr/bin/apt", O_RDONLY)
    if fd2 >= 0 {
      close(fd2)
      return true
    }

    // ── Method 15: Dopamine indicator — check for typical arm64e exploitation artifacts
    // Dopamine stages its bootstrap in /private/preboot/<UUID>/jb/.
    // We scan the preboot directory for any subdirectory containing a "jb" subfolder.
    if let prebootDir = try? FileManager.default.contentsOfDirectory(atPath: "/private/preboot") {
      for entry in prebootDir {
        let jbPath = "/private/preboot/\(entry)/jb"
        if FileManager.default.fileExists(atPath: jbPath) { return true }
      }
    }

    // ── Method 16: Exception port probe (debugger / jailbreak daemon detection) ─
    // On jailbroken devices, exception ports are often stolen by the jailbreak
    // daemon. We probe our own exception port; if it is set to an external task
    // port, someone else is watching our exceptions.
    //
    // EXC_MASK_ALL was removed from the public iOS SDK in Xcode 14+.
    // It is defined as bits 0–10 inclusive (0x7FF) in the publicly documented
    // Mach exception mask table. We define it locally to avoid the missing symbol.
    let EXC_MASK_ALL_LOCAL: exception_mask_t = (1 << 11) - 1
    // mach_port_t is UInt32 on 32-bit and UInt on 64-bit (typealiased to natural_t).
    // MACH_PORT_NULL is defined in the Darwin headers as `0` (a plain integer literal)
    // but Swift's strict type system rejects `mach_port_t = MACH_PORT_NULL` when
    // MACH_PORT_NULL resolves to a differently-sized integer constant (Int vs UInt).
    // The safe, SDK-version-independent initialisation is to cast the integer literal
    // 0 to mach_port_t directly — this is always well-defined and matches the C macro.
    var exceptionPort: mach_port_t = mach_port_t(0)
    // task_get_exception_ports signature (Darwin.Mach):
    //   func task_get_exception_ports(
    //     _ task: task_t,
    //     _ exception_mask: exception_mask_t,
    //     _ masks: exception_mask_array_t?,          ← nil
    //     _ masksCnt: UnsafeMutablePointer<mach_msg_type_number_t>?,  ← nil
    //     _ old_handlers: exception_handler_array_t?,  ← &exceptionPort (cast below)
    //     _ old_behaviors: exception_behavior_array_t?,  ← nil
    //     _ old_flavors: exception_flavor_array_t?    ← nil
    //   ) -> kern_return_t
    let kr = task_get_exception_ports(
      mach_task_self_,
      EXC_MASK_ALL_LOCAL,
      nil, nil, &exceptionPort, nil, nil
    )
    _ = kr  // result is a heuristic signal only; see comment above

    // ── Method 17: Sysctl CPU type anomaly ───────────────────────────────────
    // Palera1n and some Dopamine variants run on device types where the reported
    // hw.machine string has been patched to hide the SoC. On stock devices,
    // hw.machine always returns a valid Apple chip identifier (e.g. "iPhone14,2").
    var hwMachine = [CChar](repeating: 0, count: 256)
    var hwMachineSize = hwMachine.count
    sysctlbyname("hw.machine", &hwMachine, &hwMachineSize, nil, 0)
    let machineStr = String(cString: hwMachine)
    // A jailbreak that patches the sysctl table may return an empty string or
    // a placeholder. Neither is valid on a real Apple device.
    if machineStr.isEmpty || machineStr == "unknown" { return true }

    return false
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — 2. DEBUGGER DETECTION
  // ────────────────────────────────────────────────────────────────────────────
  // sysctl P_TRACED is the standard Apple-recommended technique (no private APIs).
  // We intentionally do NOT call ptrace(PT_DENY_ATTACH) — that terminates the
  // process when a legitimate debugger later attaches and fails App Store review.

  private func checkDebuggerAttachedSafe() -> Bool {
    var info = kinfo_proc()
    var mib: [Int32] = [CTL_KERN, KERN_PROC, KERN_PROC_PID, getpid()]
    var size = MemoryLayout<kinfo_proc>.stride
    let result = sysctl(&mib, UInt32(mib.count), &info, &size, nil, 0)
    if result == 0, (info.kp_proc.p_flag & P_TRACED) != 0 { return true }
    // isatty: stdin is a TTY only when launched from Xcode / terminal
    if isatty(STDIN_FILENO) != 0 { return true }
    return false
  }

  @objc(isDebuggerAttached:rejecter:)
  func isDebuggerAttached(
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    resolve(checkDebuggerAttachedSafe())
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — 3. SCREEN RECORDING DETECTION
  // ────────────────────────────────────────────────────────────────────────────
  // UIScreen.isCaptured covers: AirPlay Mirroring, QuickTime, ReplayKit, SharePlay.

  private func checkScreenRecordingSafe() -> Bool {
    return UIScreen.main.isCaptured
  }

  // ── Timer-based monitor for event emission ───────────────────────────────────
  private func startScreenRecordingMonitor() {
    DispatchQueue.main.async { [weak self] in
      guard let self = self else { return }
      self.recordingMonitorTimer?.invalidate()
      // Poll every 0.5 s — matches Android side cadence
      self.recordingMonitorTimer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
        guard let self = self, self.hasListeners else { return }
        let isRecording = UIScreen.main.isCaptured
        if isRecording != self.lastRecordingState {
          self.lastRecordingState = isRecording
          let eventName = isRecording ? self.EVENT_RECORDING_STARTED : self.EVENT_RECORDING_STOPPED
          self.sendEvent(withName: eventName, body: nil)
        }
      }
    }

    // Also subscribe to UIScreen.capturedDidChangeNotification (iOS 11+)
    recordingObserver = NotificationCenter.default.addObserver(
      forName: UIScreen.capturedDidChangeNotification,
      object: nil,
      queue: .main
    ) { [weak self] _ in
      guard let self = self, self.hasListeners else { return }
      let isRecording = UIScreen.main.isCaptured
      self.lastRecordingState = isRecording
      let eventName = isRecording ? self.EVENT_RECORDING_STARTED : self.EVENT_RECORDING_STOPPED
      self.sendEvent(withName: eventName, body: nil)
    }
  }

  private func stopScreenRecordingMonitor() {
    recordingMonitorTimer?.invalidate()
    recordingMonitorTimer = nil
    if let obs = recordingObserver {
      NotificationCenter.default.removeObserver(obs)
      recordingObserver = nil
    }
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — 4. SCREENSHOT DETECTION
  // ────────────────────────────────────────────────────────────────────────────
  // UIApplication.userDidTakeScreenshotNotification fires reliably after
  // the user presses Home+Power (or swipes up + Power on Face ID devices).
  // Note: this fires AFTER the screenshot is taken — we cannot prevent it.
  // Action: log the event, report violation, optionally blur content.

  private func startScreenshotMonitor() {
    screenshotObserver = NotificationCenter.default.addObserver(
      forName: UIApplication.userDidTakeScreenshotNotification,
      object: nil,
      queue: .main
    ) { [weak self] _ in
      guard let self = self, self.hasListeners else { return }
      self.sendEvent(withName: self.EVENT_SCREENSHOT_TAKEN, body: nil)
    }
  }

  private func stopScreenshotMonitor() {
    if let obs = screenshotObserver {
      NotificationCenter.default.removeObserver(obs)
      screenshotObserver = nil
    }
  }

  // Direct query (for getSecurityFlags batch call — does not need timer)
  @objc(isScreenBeingRecorded:rejecter:)
  func isScreenBeingRecorded(
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    resolve(checkScreenRecordingSafe())
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — 5. VPN DETECTION
  // ────────────────────────────────────────────────────────────────────────────
  //
  // FALSE-POSITIVE FIX — v2 (two-gate check)
  //
  // The previous single-gate implementation called getifaddrs() and returned
  // true whenever ANY interface name started with "utun". This is incorrect:
  // iOS always creates utun0, utun1, utun2 (and often more) as permanent
  // SYSTEM interfaces for Continuity / Handoff, AirDrop, and iCloud Private
  // Relay's Network Extension — completely independent of user-configured VPNs.
  // These interfaces are present in getifaddrs() output on EVERY physical
  // iPhone regardless of VPN state, causing a 100% false-positive rate.
  //
  // Correct approach — BOTH gates must pass:
  //
  //   Gate 1 (NWPathMonitor):
  //     Query the active best network path. On a device with no VPN active,
  //     the path uses .wifi or .cellular. System utun interfaces (Continuity,
  //     AirDrop, Private Relay) do NOT become the active path transport —
  //     only the primary interface does. If the path uses only
  //     .wifi / .cellular / .loopback / .wiredEthernet → return false immediately.
  //     A real active VPN tunnel routes traffic through an interface that
  //     NWPath classifies as .other (no standard type).
  //
  //   Gate 2 (getifaddrs + IFF_UP):
  //     Only runs when Gate 1 says the active path uses a non-standard
  //     interface type. Scans for utun* / ipsec* / ppp* interfaces where
  //     the IFF_UP flag is set (interface is allocated AND active).
  //     A VPN profile that is installed but disconnected will NOT have
  //     IFF_UP set → Gate 2 fails → result = false.
  //
  // "tun" prefix (without "utun") is intentionally removed. It does not
  // exist on stock iOS (only Linux/Android TUN kernel devices use it).
  // Keeping it risks matching future system interfaces with no benefit.
  //
  // VPN types correctly detected:
  //   Personal VPN (IKEv2/IPSec/L2TP) in Settings → VPN: utun* UP + path .other
  //   WireGuard / OpenVPN / Tailscale / Cloudflare WARP (packet-tunnel): same
  //   Per-app VPN: same
  //
  // Cases that no longer false-positive:
  //   System utun (Continuity/AirDrop): present but path = .wifi/.cellular
  //   iCloud Private Relay: Apple surfaces it as .wifi/.cellular to NWPath
  //   VPN profile installed but not connected: utun not UP

  private func checkVPNSafe() -> Bool {
    // ── Gate 1: NWPathMonitor — is the active path using a non-standard interface? ──
    //
    // We start a one-shot NWPathMonitor and wait up to 300 ms for its first
    // pathUpdateHandler callback. If the handler fires and ALL active interfaces
    // on the path are .wifi / .cellular / .loopback / .wiredEthernet, the
    // active transport is a standard interface — no VPN tunnel is routing
    // traffic — and we return false immediately without scanning interfaces.
    //
    // 300 ms timeout: NWPathMonitor normally fires within milliseconds on a
    // connected device. The generous timeout guards against edge cases (brief
    // radio sleep). On timeout we fall through to Gate 2 (conservative path).
    let monitor  = NWPathMonitor()
    let sema     = DispatchSemaphore(value: 0)
    var activePathHasNonStandardInterface = false

    monitor.pathUpdateHandler = { path in
      // Check whether the path uses any interface type that is NOT a standard
      // known transport. Standard types (.wifi, .cellular, .loopback,
      // .wiredEthernet) never carry active VPN tunnels as the primary transport.
      let nonStandard = path.availableInterfaces.contains { iface in
        path.usesInterfaceType(iface.type)    // interface is actually used by path
          && iface.type != .wifi
          && iface.type != .cellular
          && iface.type != .loopback
          && iface.type != .wiredEthernet
      }
      activePathHasNonStandardInterface = nonStandard
      sema.signal()
    }
    let q = DispatchQueue(label: "medacademy.vpn.pathcheck", qos: .userInitiated)
    monitor.start(queue: q)
    let timedOut = sema.wait(timeout: .now() + 0.3) == .timedOut
    monitor.cancel()

    if timedOut {
#if DEBUG
      NSLog("[IOSSecurityModule][VPN] Gate-1: NWPathMonitor timed out — proceeding to Gate-2")
#endif
      // Conservative: let Gate 2 decide if we couldn't get a path update
    } else if !activePathHasNonStandardInterface {
#if DEBUG
      NSLog("[IOSSecurityModule][VPN] Gate-1 FAIL — path uses only wifi/cellular/loopback → no VPN")
#endif
      return false  // Active path is standard transport → definitely no VPN routing
    } else {
#if DEBUG
      NSLog("[IOSSecurityModule][VPN] Gate-1 PASS — path uses non-standard interface type")
#endif
    }

    // ── Gate 2: getifaddrs + IFF_UP — is a VPN-type interface actually UP? ──
    //
    // Only reached when Gate 1 detected a non-standard path (or timed out).
    // We confirm by checking that a VPN-prefixed interface has IFF_UP set.
    // IFF_UP means the interface is both allocated AND currently active.
    // A VPN that is configured but not connected will NOT have IFF_UP.
    var ifaddr: UnsafeMutablePointer<ifaddrs>?
    guard getifaddrs(&ifaddr) == 0, let firstAddr = ifaddr else {
#if DEBUG
      NSLog("[IOSSecurityModule][VPN] Gate-2: getifaddrs() failed → returning false")
#endif
      return false
    }
    defer { freeifaddrs(ifaddr) }

    var ptr = firstAddr
    while true {
      let iface = ptr.pointee
      if let nameCStr = iface.ifa_name {
        let name  = String(cString: nameCStr)
        let flags = Int32(iface.ifa_flags)
        let isUp  = (flags & IFF_UP) != 0
        // utun* — all iOS VPN types: IKEv2, IPSec, WireGuard, packet-tunnel ext
        // ipsec* — legacy kernel IPSec interface (older iOS VPN stacks)
        // ppp*   — L2TP/PPPoE-based VPN tunnels
        // "tun" WITHOUT "utun" prefix intentionally omitted: stock iOS does not
        // create bare "tun" interfaces; only Linux/Android TUN devices do.
        let isVpnPrefix = name.hasPrefix("utun") || name.hasPrefix("ipsec") || name.hasPrefix("ppp")
#if DEBUG
        if isVpnPrefix {
          NSLog("[IOSSecurityModule][VPN] Gate-2 candidate: name=%@ flags=0x%X isUp=%@",
                name, flags, isUp ? "YES" : "NO")
        }
#endif
        if isVpnPrefix && isUp {
#if DEBUG
          NSLog("[IOSSecurityModule][VPN] Gate-2 PASS — VPN interface UP: %@", name)
          NSLog("[IOSSecurityModule][VPN] Final: VPN ACTIVE")
#endif
          return true
        }
      }
      guard let next = iface.ifa_next else { break }
      ptr = next
    }

#if DEBUG
    NSLog("[IOSSecurityModule][VPN] Gate-2 FAIL — no VPN interface found with IFF_UP")
    NSLog("[IOSSecurityModule][VPN] Final: NO VPN")
#endif
    return false
  }

  @objc(isVPNDetected:rejecter:)
  func isVPNDetected(
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    resolve(checkVPNSafe())
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — 6. PROXY DETECTION
  // ────────────────────────────────────────────────────────────────────────────
  // CFNetworkCopySystemProxySettings — returns nil on error; we fail-safe to false.
  //
  // kCFNetworkProxiesHTTPSEnable / kCFNetworkProxiesSOCKSEnable and their *Proxy
  // counterparts were removed from the Swift-visible CFNetwork public API in the
  // iOS 17 SDK (Xcode 15). The underlying CFDictionary key strings are unchanged
  // and still populated at runtime — we use the raw string literals directly.
  //
  // String key values (from CFProxySupport.h, unchanged across all iOS versions):
  //   HTTPEnable  = "HTTPEnable"    HTTPProxy  = "HTTPProxy"
  //   HTTPSEnable = "HTTPSEnable"   HTTPSProxy = "HTTPSProxy"
  //   SOCKSEnable = "SOCKSEnable"   SOCKSProxy = "SOCKSProxy"

  private func checkProxySafe() -> Bool {
    guard let raw = CFNetworkCopySystemProxySettings(),
          let settings = raw.takeRetainedValue() as? [String: Any] else { return false }

    // Check enable flags first — proxy key can exist but be disabled.
    // kCFNetworkProxiesHTTPEnable is still available (not removed); the others use literals.
    let httpEnabled  = (settings[kCFNetworkProxiesHTTPEnable  as String] as? Int) == 1
    let httpsEnabled = (settings["HTTPSEnable"]  as? Int) == 1
    let socksEnabled = (settings["SOCKSEnable"] as? Int) == 1

    if httpEnabled,
       let host = settings[kCFNetworkProxiesHTTPProxy as String] as? String,
       !host.isEmpty { return true }
    if httpsEnabled,
       let host = settings["HTTPSProxy"] as? String,
       !host.isEmpty { return true }
    if socksEnabled,
       let host = settings["SOCKSProxy"] as? String,
       !host.isEmpty { return true }
    return false
  }

  @objc(isProxyDetected:rejecter:)
  func isProxyDetected(
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    resolve(checkProxySafe())
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — 7. DYLIB INJECTION / FRIDA DETECTION (expanded)
  // ────────────────────────────────────────────────────────────────────────────
  // Covers: Frida-gadget, Cycript, Ellekit, SSL kill-switch, Reveal, Flex,
  //         and all major tweak injection frameworks.

  private func checkDylibInjectionSafe() -> Bool {
    let suspiciousTokens = [
      "frida", "gadget", "cynject",
      "substitute", "substrate", "libhooker",
      "tweakinject", "ellekit", "libellekit",
      "ssllibpatch", "ssl-killswitch",        // SSL pinning bypass tools
      "revealserver",                          // Reveal UI inspector
      "flexdylib",                             // Flex tweak injector
      "objection",                             // Objection framework
      "cycript",                               // Cycript runtime
    ]
    let count = _dyld_image_count()
    for i in 0..<count {
      guard let raw = _dyld_get_image_name(i) else { continue }
      let lower = String(cString: raw).lowercased()
      for token in suspiciousTokens {
        if lower.contains(token) { return true }
      }
    }
    // DYLD_INSERT_LIBRARIES is always set by Frida's standard injection method
    if ProcessInfo.processInfo.environment["DYLD_INSERT_LIBRARIES"] != nil { return true }
    return false
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — 8. BUNDLE / BINARY INTEGRITY (Anti-Tamper) — hardened
  // ────────────────────────────────────────────────────────────────────────────
  // Checks:
  //   A) MachO magic bytes — must be a valid ARM64/fat binary value
  //   B) MachO flags — CS_VALID flag in load commands (code-signing status)
  //   C) LC_ENCRYPTION_INFO / LC_ENCRYPTION_INFO_64 load command
  //      App Store binaries always contain this command (FairPlay encryption stub).
  //      Its absence means the binary was never through App Store processing,
  //      i.e. it was sideloaded, enterprise-resigned, or cracked.
  //      NOTE: Debug / development builds also lack this command. We combine
  //      this with CS_VALID and the release-channel check at JS layer.

  private func checkBundleIntegritySafe() -> Bool {
    // _MH_EXECUTE_HEADER is unreliable with the Xcode 15+ new linker (ld-prime).
    // The symbol exists but its Swift binding breaks under certain ASLR / LTO configs.
    // _dyld_get_image_header(0) is the canonical, always-correct way to get the
    // main executable's Mach-O header pointer — it accounts for the ASLR slide and
    // is guaranteed to point to the currently loaded image header.
    guard let rawHeader = _dyld_get_image_header(0) else {
      return false // extremely unlikely; fail-open to avoid false positives
    }
    // Reinterpret as mach_header_64 (all modern iOS devices are arm64)
    let header = rawHeader.withMemoryRebound(to: mach_header_64.self, capacity: 1) { $0 }

    // Check A: MachO header magic
    let magic = header.pointee.magic
    let validMagics: [UInt32] = [MH_MAGIC_64, MH_CIGAM_64, MH_MAGIC, MH_CIGAM, FAT_MAGIC, FAT_CIGAM]
    if !validMagics.contains(magic) { return true }

    // Check B: MachO flags — CS_VALID (0x1) indicates code signing is intact.
    // A resigner that patches the binary but fails to re-sign will leave CS_VALID unset.
    let flags = header.pointee.flags
    let CS_VALID: UInt32 = 0x00000001
    if (flags & CS_VALID) == 0 && flags != 0 { return true }

    // Check C: LC_ENCRYPTION_INFO / LC_ENCRYPTION_INFO_64 presence
    // App Store distributed binaries always have this; cracked/sideloaded ones do not.
    var encryptionFound = false
    let ncmds = Int(header.pointee.ncmds)
    var lcPtr = UnsafeRawPointer(header) + MemoryLayout<mach_header_64>.size
    for _ in 0..<ncmds {
      let lc = lcPtr.load(as: load_command.self)
      if lc.cmd == LC_ENCRYPTION_INFO || lc.cmd == LC_ENCRYPTION_INFO_64 {
        encryptionFound = true
        break
      }
      lcPtr = lcPtr + Int(lc.cmdsize)
    }
    // CS_DEBUGGED (0x10000000): set on debug/dev builds; skip encryption check for those.
    let CS_DEBUGGED: UInt32 = 0x10000000
    let isDebugBuild = (flags & CS_DEBUGGED) != 0
    if !encryptionFound && !isDebugBuild { return true }

    return false
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — 9. APP ATTEST (iOS 14+ equivalent of Play Integrity) — hardened
  // ────────────────────────────────────────────────────────────────────────────
  // Flow: generateKey → attestKey (once, server-side) → generateAssertion (per-request).
  // Key lifecycle:
  //   • generateKey() creates a new Secure Enclave key and returns a keyId.
  //   • JS layer stores keyId in expo-secure-store.
  //   • On subsequent launches JS reads stored keyId and calls generateAssertion directly.
  //   • If assertKey() / generateAssertion() returns DCError.invalidKey, JS calls
  //     generateAppAttestKey again to regenerate (this method rejects with error code
  //     "APP_ATTEST_INVALID_KEY" so the JS layer can distinguish it from transient errors).
  //
  // Error code semantics:
  //   APP_ATTEST_UNAVAILABLE   — iOS < 14 (not a supported device for this check)
  //   APP_ATTEST_UNSUPPORTED   — Simulator or A11 and older chip (use DeviceCheck fallback)
  //   APP_ATTEST_INVALID_KEY   — Key invalidated by Apple; caller MUST regenerate
  //   APP_ATTEST_SERVER_ERROR  — Transient; caller should retry, not regenerate
  //   APP_ATTEST_KEY_ERROR     — Other key generation failure
  //   APP_ATTEST_ATTEST_ERROR  — Attestation failure (server or hardware error)
  //   APP_ATTEST_ASSERTION_ERROR — Assertion generation failure

  @objc(generateAppAttestKey:rejecter:)
  func generateAppAttestKey(
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    guard #available(iOS 14.0, *) else {
      reject("APP_ATTEST_UNAVAILABLE", "App Attest requires iOS 14+", nil)
      return
    }
    let service = DCAppAttestService.shared
    guard service.isSupported else {
      reject("APP_ATTEST_UNSUPPORTED", "App Attest not supported on this device — use DeviceCheck", nil)
      return
    }
    service.generateKey { keyId, error in
      if let error = error {
        reject("APP_ATTEST_KEY_ERROR", error.localizedDescription, error)
        return
      }
      guard let keyId = keyId else {
        reject("APP_ATTEST_KEY_ERROR", "generateKey returned nil keyId", nil)
        return
      }
      resolve(keyId)
    }
  }

  @objc(attestAppAttestKey:clientDataHash:resolver:rejecter:)
  func attestAppAttestKey(
    keyId: String,
    clientDataHash: String,
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    guard #available(iOS 14.0, *) else {
      reject("APP_ATTEST_UNAVAILABLE", "App Attest requires iOS 14+", nil)
      return
    }
    // Parameter validation — reject obviously malformed inputs immediately.
    // keyId must be a non-empty string (Apple returns a UUID-like identifier).
    // clientDataHash must be a non-empty base64 string that decodes to exactly 32 bytes (SHA-256).
    guard !keyId.isEmpty, keyId.count <= 256 else {
      reject("APP_ATTEST_INVALID_PARAM", "keyId must be a non-empty string ≤ 256 chars", nil)
      return
    }
    guard !clientDataHash.isEmpty, clientDataHash.count <= 512 else {
      reject("APP_ATTEST_INVALID_PARAM", "clientDataHash must be a non-empty base64 string ≤ 512 chars", nil)
      return
    }
    guard let hashData = Data(base64Encoded: clientDataHash), hashData.count == 32 else {
      reject("APP_ATTEST_INVALID_HASH", "clientDataHash must be base64-encoded SHA-256 (32 bytes)", nil)
      return
    }
    DCAppAttestService.shared.attestKey(keyId, clientDataHash: hashData) { attestObject, error in
      if let error = error {
        // Distinguish permanent key invalidation from transient server errors
        let nsErr = error as NSError
        if nsErr.domain == "DCErrorDomain" {
          if nsErr.code == DCError.invalidKey.rawValue {
            reject("APP_ATTEST_INVALID_KEY", "Key invalidated — regenerate required", error)
            return
          }
          if nsErr.code == DCError.serverUnavailable.rawValue {
            reject("APP_ATTEST_SERVER_ERROR", "Apple attestation server unavailable — retry", error)
            return
          }
        }
        reject("APP_ATTEST_ATTEST_ERROR", error.localizedDescription, error)
        return
      }
      guard let obj = attestObject else {
        reject("APP_ATTEST_ATTEST_ERROR", "attestKey returned nil object", nil)
        return
      }
      resolve(obj.base64EncodedString())
    }
  }

  @objc(generateAppAttestAssertion:challenge:resolver:rejecter:)
  func generateAppAttestAssertion(
    keyId: String,
    challenge: String,
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    guard #available(iOS 14.0, *) else {
      reject("APP_ATTEST_UNAVAILABLE", "App Attest requires iOS 14+", nil)
      return
    }
    // Parameter validation — keyId and challenge must be non-empty and within
    // reasonable size bounds to prevent memory exhaustion or bridge abuse.
    guard !keyId.isEmpty, keyId.count <= 256 else {
      reject("APP_ATTEST_INVALID_PARAM", "keyId must be a non-empty string ≤ 256 chars", nil)
      return
    }
    // Challenge is a server-issued nonce (typically 32–128 bytes when base64-encoded).
    // Cap at 1024 chars to guard against oversized input from a compromised JS layer.
    guard !challenge.isEmpty, challenge.count <= 1024 else {
      reject("APP_ATTEST_INVALID_CHALLENGE", "challenge must be a non-empty string ≤ 1024 chars", nil)
      return
    }
    guard let challengeData = challenge.data(using: .utf8) else {
      reject("APP_ATTEST_INVALID_CHALLENGE", "challenge must be a valid UTF-8 string", nil)
      return
    }
    // SHA-256 hash required by App Attest assertion API
    let hash = Data(SHA256.hash(data: challengeData))
    DCAppAttestService.shared.generateAssertion(keyId, clientDataHash: hash) { assertionData, error in
      if let error = error {
        let nsErr = error as NSError
        // Permanent key invalidation: JS must regenerate the key then re-attest
        if nsErr.domain == "DCErrorDomain", nsErr.code == DCError.invalidKey.rawValue {
          reject("APP_ATTEST_INVALID_KEY", "Key invalidated — regenerate required", error)
          return
        }
        if nsErr.domain == "DCErrorDomain", nsErr.code == DCError.serverUnavailable.rawValue {
          reject("APP_ATTEST_SERVER_ERROR", "Apple assertion server unavailable — retry", error)
          return
        }
        reject("APP_ATTEST_ASSERTION_ERROR", error.localizedDescription, error)
        return
      }
      guard let data = assertionData else {
        reject("APP_ATTEST_ASSERTION_ERROR", "generateAssertion returned nil", nil)
        return
      }
      resolve(data.base64EncodedString())
    }
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — 10. DEVICECHECK (fallback when App Attest is unavailable) — hardened
  // ────────────────────────────────────────────────────────────────────────────
  // DCDevice generates a per-device token validated by Apple's servers.
  // Weaker than App Attest (proves real device, not app authenticity).
  // Used ONLY when App Attest is genuinely unavailable:
  //   • Simulator (DCAppAttestService.isSupported == false)
  //   • iOS < 14
  //   • A11 or older SoC (iPhone 8 and older)
  //
  // NOT used for transient App Attest server errors — those should be retried.
  //
  // Error code semantics:
  //   DEVICE_CHECK_UNSUPPORTED — genuine unavailability (simulator, non-Apple device)
  //   DEVICE_CHECK_ERROR       — token generation failure

  @objc(generateDeviceCheckToken:rejecter:)
  func generateDeviceCheckToken(
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    guard DCDevice.current.isSupported else {
      reject("DEVICE_CHECK_UNSUPPORTED", "DeviceCheck not supported on this device", nil)
      return
    }
    DCDevice.current.generateToken { tokenData, error in
      if let error = error {
        reject("DEVICE_CHECK_ERROR", error.localizedDescription, error)
        return
      }
      guard let data = tokenData else {
        reject("DEVICE_CHECK_ERROR", "generateToken returned nil", nil)
        return
      }
      resolve(data.base64EncodedString())
    }
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — CONVENIENCE INDIVIDUAL METHODS (crash-resistant, safe-method names)
  // ────────────────────────────────────────────────────────────────────────────

  @objc(isJailbreakDetected:rejecter:)
  func isJailbreakDetected(
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    DispatchQueue.global(qos: .userInitiated).async { [weak self] in
      resolve(self?.checkJailbreakSafe() ?? false)
    }
  }

  @objc(isDylibInjectionDetected:rejecter:)
  func isDylibInjectionDetected(
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    DispatchQueue.global(qos: .userInitiated).async { [weak self] in
      resolve(self?.checkDylibInjectionSafe() ?? false)
    }
  }

  @objc(isBundleTampered:rejecter:)
  func isBundleTampered(
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    resolve(checkBundleIntegritySafe())
  }
}
