// IOSSecurityModule.swift
// MedAcademy — iOS Native Security Module  (v428 — Final Hardening Pass)
//
// Comprehensive iOS security checks injected during Expo prebuild.
// All methods are App Store compliant — no private APIs used.
//
// ─── Checks implemented ───────────────────────────────────────────────────────
//  Jailbreak      — 17 independent heuristics (hardened for Dopamine/RootHide/Palera1n)
//  Debugger       — sysctl kinfo_proc + isatty
//  Anti-hooking   — ObjC IMP swizzle detection for 4 critical selectors
//  Screen capture — UIScreen.isCaptured (recording) + UIScreen.didConnect (external display)
//  Screenshot     — UIApplication.userDidTakeScreenshot notification
//  VPN            — network interface scan (utun/ipsec/ppp) + NWPathMonitor
//  Proxy          — CFNetworkCopySystemProxySettings
//  Dylib scan     — injected library detection via dyld image enumeration (expanded)
//  Bundle tamper  — _MH_EXECUTE_HEADER magic + CS_VALID + LC_ENCRYPTION_INFO
//  App Attest     — DCAppAttestService (iOS 14+) — key generation, attestation, assertion
//                   Note: App Attest keys are Secure Enclave-backed by the OS (A12+).
//                   The keyId is a reference to an SE hardware key; the private key
//                   never leaves the Secure Enclave. This is functionally equivalent
//                   to kSecAttrTokenIDSecureEnclave but managed by DCAppAttestService.
//  DeviceCheck    — DCDevice fallback (real device proof when App Attest unavailable)
//  Secure storage — Keychain (via expo-secure-store at JS layer, ThisDeviceOnly variants)
//  Runtime events — RCTEventEmitter for recording start/stop + screenshot
//  Security log   — All detections emit structured log events to JS unified logging
//
// ─── Crash resistance ────────────────────────────────────────────────────────
//  Every method wraps its body in do-catch or guard.
//  No method throws to the RN bridge — all errors are caught and converted to
//  reject() calls or safe boolean defaults.
//  All OS-version-gated APIs are guarded with #available().
//
// ─── Logging policy ──────────────────────────────────────────────────────────
//  All logs wrapped in #if DEBUG. Production builds emit zero log output.
//  Sensitive values (keyIds, attestation objects, tokens, challenges) are
//  never logged even in DEBUG — they are redacted to first-8-chars + "…".
//
// ─── Deployment target: iOS 15.1+ (matches app.json) ─────────────────────────
// All API calls are availability-guarded for OS version compatibility.

import Foundation
import UIKit
import Network
import NetworkExtension
import DeviceCheck
import CryptoKit
import MachO
import Darwin

// ─── React Native bridge ──────────────────────────────────────────────────────
// The @objc / NSObject inheritance is required for the RCT runtime.
// The module is registered via RCT_EXTERN_MODULE in the bridging header,
// which is generated by the withIOSSecurityModule config plugin.

@objc(IOSSecurityModule)
class IOSSecurityModule: RCTEventEmitter {

  // ── Event names ─────────────────────────────────────────────────────────────
  private let EVENT_RECORDING_STARTED  = "iOSScreenRecordingStarted"
  private let EVENT_RECORDING_STOPPED  = "iOSScreenRecordingStopped"
  private let EVENT_SCREENSHOT_TAKEN   = "iOSScreenshotTaken"

  // ── Event names (additional) ─────────────────────────────────────────────
  private let EVENT_JAILBREAK_DETECTED   = "iOSJailbreakDetected"
  private let EVENT_DEBUGGER_ATTACHED    = "iOSDebuggerAttached"
  private let EVENT_INTEGRITY_FAILED     = "iOSIntegrityFailed"

  // ── State ───────────────────────────────────────────────────────────────────
  private var hasListeners = false
  private var recordingMonitorTimer: Timer?
  private var lastRecordingState: Bool = false
  private var screenshotObserver: NSObjectProtocol?
  private var recordingObserver: NSObjectProtocol?

  // ── App Attest key cache (in-memory; JS layer persists to SecureStore) ──────
  // App Attest keys are Secure Enclave-backed: DCAppAttestService.generateKey()
  // creates a non-exportable P-256 key inside the A12+ Secure Enclave. The keyId
  // is only a public reference — the private key never leaves the SE hardware.
  // This is equivalent to kSecAttrTokenIDSecureEnclave without requiring manual
  // Keychain access control setup. See Apple docs: "Establishing Your App's Integrity".
  private static let invalidKeyErrorCodes: Set<Int> = [
    DCError.invalidKey.rawValue,        // key was invalidated by Apple — must regenerate
    // DCError.serverUnavailable is intentionally NOT here — it is transient, handled separately
  ]

  // ── Jailbreak result cache (5 s TTL — expensive multi-method check) ─────────
  private var jailbreakCacheResult: Bool? = nil
  private var jailbreakCacheExpiry: Date  = .distantPast
  private let jailbreakCacheTTL: TimeInterval = 5.0

  // ── Anti-hooking: IMP baseline store ─────────────────────────────────────────
  // Populated once in startObserving(). Keys are human-readable selector strings;
  // values are the original IMP addresses captured before any tweak can swizzle them.
  private var baselineIMPs: [String: IMP] = [:]

  // ── Secure random nonce generation ──────────────────────────────────────────
  // CSPRNG-backed nonce for write-tests; replaces arc4random() / UUID() which
  // are not cryptographically safe for security-critical path usage.
  private func secureRandomSuffix() -> String {
    var bytes = [UInt8](repeating: 0, count: 16)
    let result = SecRandomCopyBytes(kSecRandomDefault, bytes.count, &bytes)
    guard result == errSecSuccess else {
      // SecRandomCopyBytes failed — fall back to UUID (non-crypto, but rare error path)
      return UUID().uuidString
    }
    return bytes.map { String(format: "%02x", $0) }.joined()
  }

  // ── Debug redaction helper ───────────────────────────────────────────────────
  // Logs only first 8 chars of sensitive values (keyIds, tokens, attestation objects).
  // Never called in production builds.
  #if DEBUG
  private func redact(_ value: String) -> String {
    let prefix = String(value.prefix(8))
    return prefix + "…[redacted]"
  }
  #endif

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — RCTEventEmitter required overrides
  // ────────────────────────────────────────────────────────────────────────────

  override func supportedEvents() -> [String]! {
    return [
      EVENT_RECORDING_STARTED, EVENT_RECORDING_STOPPED, EVENT_SCREENSHOT_TAKEN,
      EVENT_JAILBREAK_DETECTED, EVENT_DEBUGGER_ATTACHED, EVENT_INTEGRITY_FAILED,
    ]
  }

  override static func requiresMainQueueSetup() -> Bool { return false }

  override func startObserving() {
    hasListeners = true
    startScreenRecordingMonitor()
    startScreenshotMonitor()
    captureBaselineIMPs()
  }

  override func stopObserving() {
    hasListeners = false
    stopScreenRecordingMonitor()
    stopScreenshotMonitor()
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — ANTI-HOOKING: IMP baseline capture + swizzle detection
  // ────────────────────────────────────────────────────────────────────────────
  // Called once from startObserving() — records original IMP addresses before
  // any tweak has a chance to swizzle them post-load.
  // checkAntiHookingSafe() compares live IMPs at runtime against these baselines.

  private func captureBaselineIMPs() {
    // UIScreen.isCaptured — gates screen-recording block
    if let cls = NSClassFromString("UIScreen"),
       let sel = NSSelectorFromString("isCaptured") as Selector?,
       let method = class_getInstanceMethod(cls, sel) {
      baselineIMPs["UIScreen.isCaptured"] = method_getImplementation(method)
    }
    // NSFileManager.fileExistsAtPath: — jailbreak path scan
    if let cls = NSClassFromString("NSFileManager"),
       let method = class_getInstanceMethod(cls, #selector(FileManager.fileExists(atPath:))) {
      baselineIMPs["NSFileManager.fileExistsAtPath"] = method_getImplementation(method)
    }
    // DCAppAttestService.isSupported — App Attest gate
    if #available(iOS 14.0, *),
       let cls = NSClassFromString("DCAppAttestService"),
       let method = class_getInstanceMethod(cls, NSSelectorFromString("isSupported")) {
      baselineIMPs["DCAppAttestService.isSupported"] = method_getImplementation(method)
    }
    // DCDevice.isSupported — DeviceCheck gate
    if let cls = NSClassFromString("DCDevice"),
       let method = class_getInstanceMethod(cls, NSSelectorFromString("isSupported")) {
      baselineIMPs["DCDevice.isSupported"] = method_getImplementation(method)
    }
  }

  private func checkAntiHookingSafe() -> Bool {
    guard !baselineIMPs.isEmpty else { return false } // baselines not yet captured

    var swizzled = false

    if let cls = NSClassFromString("UIScreen"),
       let sel = NSSelectorFromString("isCaptured") as Selector?,
       let method = class_getInstanceMethod(cls, sel),
       let baseline = baselineIMPs["UIScreen.isCaptured"] {
      if method_getImplementation(method) != baseline { swizzled = true }
    }

    if let cls = NSClassFromString("NSFileManager"),
       let method = class_getInstanceMethod(cls, #selector(FileManager.fileExists(atPath:))),
       let baseline = baselineIMPs["NSFileManager.fileExistsAtPath"] {
      if method_getImplementation(method) != baseline { swizzled = true }
    }

    if #available(iOS 14.0, *),
       let cls = NSClassFromString("DCAppAttestService"),
       let method = class_getInstanceMethod(cls, NSSelectorFromString("isSupported")),
       let baseline = baselineIMPs["DCAppAttestService.isSupported"] {
      if method_getImplementation(method) != baseline { swizzled = true }
    }

    if let cls = NSClassFromString("DCDevice"),
       let method = class_getInstanceMethod(cls, NSSelectorFromString("isSupported")),
       let baseline = baselineIMPs["DCDevice.isSupported"] {
      if method_getImplementation(method) != baseline { swizzled = true }
    }

    return swizzled
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — BATCH ALL FLAGS (single bridge call)
  // ────────────────────────────────────────────────────────────────────────────

  @objc(getSecurityFlags:rejecter:)
  func getSecurityFlags(
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    DispatchQueue.global(qos: .userInitiated).async { [weak self] in
      guard let self = self else { resolve([String: Any]()); return }
      // Crash-resistant: each sub-check is individually wrapped; one failure
      // does not prevent the others from returning their results.
      let jailbroken      = self.checkJailbreakSafe()
      let debuggerAttach  = self.checkDebuggerAttachedSafe()
      let screenRecording = self.checkScreenRecordingSafe()
      let vpn             = self.checkVPNSafe()
      let proxy           = self.checkProxySafe()
      let dylibInjection  = self.checkDylibInjectionSafe()
      let bundleTampered  = self.checkBundleIntegritySafe()
      let hookDetected    = self.checkAntiHookingSafe()

      let flags: [String: Any] = [
        "jailbreakDetected":      jailbroken,
        "debuggerAttached":       debuggerAttach,
        "screenBeingRecorded":    screenRecording,
        "vpnDetected":            vpn,
        "proxyDetected":          proxy,
        "dylibInjectionDetected": dylibInjection || hookDetected, // dylib OR IMP swizzle
        "bundleTampered":         bundleTampered,
        "hookDetected":           hookDetected,
        // Android-only fields — always false on iOS
        "developerOptionsEnabled": false,
        "adbEnabled":              false,
        // fridaDetected: dylib injection scan covers Frida-on-iOS;
        // IMP swizzle catches Substrate-based hooks that rename their dylib.
        "fridaDetected":           dylibInjection || hookDetected,
        "xposedDetected":          false,
        "magiskDetected":          false,
        "overlayDetected":         false,
        "signatureValid":          !bundleTampered,
        "tampered":                bundleTampered,
        "testOnlyBuild":           false,
      ]
      resolve(flags)

      // Emit targeted events for JS logging pipeline — fires AFTER resolve()
      // so the batch result is available to the caller immediately.
      if jailbroken     { self.emitSecurityEvent(self.EVENT_JAILBREAK_DETECTED, detail: "jailbreak") }
      if debuggerAttach { self.emitSecurityEvent(self.EVENT_DEBUGGER_ATTACHED,  detail: "debugger") }
      if bundleTampered { self.emitSecurityEvent(self.EVENT_INTEGRITY_FAILED,   detail: "bundle_tamper") }
      if hookDetected   { self.emitSecurityEvent(self.EVENT_INTEGRITY_FAILED,   detail: "imp_swizzle") }
    }
  }

  // ── Unified event emission helper ────────────────────────────────────────────
  private func emitSecurityEvent(_ name: String, detail: String) {
    guard hasListeners else { return }
    sendEvent(withName: name, body: ["detail": detail, "ts": Date().timeIntervalSince1970])
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — 1. JAILBREAK DETECTION (17 methods — hardened for Dopamine/RootHide/Palera1n)
  // ────────────────────────────────────────────────────────────────────────────
  // Multiple independent heuristics — evasion of one must not bypass the system.
  // Returns true if ANY check fires.
  //
  // Jailbreak landscape covered:
  //  • checkra1n / unc0ver (pre-A12 / A12+)
  //  • Palera1n (arm64e, rootless, /var/jb mountpoint)
  //  • Dopamine (arm64e, rootless, XinaA15/Fugu15 successor)
  //  • RootHide (hides jailbreak artifacts from apps — bypassed by methods 12-17)
  //  • Serotonin / Misaka / Ellekit-based jailbreaks
  //  • Legacy: Cydia/Sileo/unc0ver-era paths

  // Crash-resistant wrapper — never throws to caller
  private func checkJailbreakSafe() -> Bool {
    // Use 5-second in-memory cache: jailbreak state cannot change at runtime
    let now = Date()
    if let cached = jailbreakCacheResult, now < jailbreakCacheExpiry {
      return cached
    }
    let result = checkJailbreak()
    jailbreakCacheResult = result
    jailbreakCacheExpiry = now.addingTimeInterval(jailbreakCacheTTL)
    return result
  }

  private func checkJailbreak() -> Bool {
    // ── Method 1: Known jailbreak app/binary/tool paths ─────────────────────
    // Covers: unc0ver, Taurine, Sileo, Zebra, Filza, Dopamine, Palera1n, Serotonin,
    //         Misaka, RootHide bootstrap, Ellekit, and common system-level indicators.
    let jailbreakPaths: [String] = [
      // Package managers
      "/Applications/Cydia.app",
      "/Applications/Sileo.app",
      "/Applications/Zebra.app",
      "/Applications/Installer.app",
      "/Applications/Filza.app",
      // Palera1n / Dopamine / rootless jailbreak mountpoints
      "/var/jb",
      "/var/jb/usr/bin/apt",
      "/var/jb/usr/bin/bash",
      "/var/jb/Applications/Sileo.app",
      "/var/jb/Applications/Zebra.app",
      "/var/jb/Library/MobileSubstrate",
      // RootHide bootstrap artifacts (before hide takes effect)
      "/var/jb/.installed_dopamine",
      "/var/jb/.installed_palera1n",
      "/var/jb/.installed_rootless",
      // Dopamine-specific
      "/private/preboot/tmp/dopamine",
      "/var/mobile/.DO_NOT_DELETE_dopamine",
      // SSH / APT binaries (classic full-root jailbreaks)
      "/usr/sbin/sshd",
      "/usr/bin/sshd",
      "/usr/libexec/ssh-keysign",
      "/usr/bin/ssh",
      "/etc/apt",
      "/etc/apt/sources.list",
      "/var/lib/dpkg/info",
      "/var/lib/apt",
      "/var/cache/apt",
      // Tweak injection frameworks
      "/Library/MobileSubstrate/MobileSubstrate.dylib",
      "/Library/MobileSubstrate/DynamicLibraries",
      "/usr/lib/libsubstitute.dylib",
      "/usr/lib/libhooker.dylib",
      "/usr/lib/TweakInject.dylib",
      "/usr/lib/substrate/SubstrateBootstrap.dylib",
      "/usr/lib/ellekit.dylib",
      "/usr/lib/libellekit.dylib",
      "/var/containers/Bundle/tweakinject.dylib",
      // Shell binaries (stock iOS has /bin/sh as a symlink to /private/var/select/sh;
      // a writable real file at /bin/bash is a strong jailbreak indicator)
      "/bin/bash",
      "/usr/local/bin/theos",
    ]
    for path in jailbreakPaths {
      if FileManager.default.fileExists(atPath: path) { return true }
    }

    // ── Method 2: Cydia URL scheme ───────────────────────────────────────────
    if let url = URL(string: "cydia://package/com.example.package") {
      if UIApplication.shared.canOpenURL(url) { return true }
    }
    // Sileo URL scheme (rootless-era package manager)
    if let url = URL(string: "sileo://package/com.example.package") {
      if UIApplication.shared.canOpenURL(url) { return true }
    }

    // ── Method 3: Sandbox write test ─────────────────────────────────────────
    // On stock iOS, writing to /private fails with EPERM (sandbox restriction).
    // On jailbroken devices the sandbox is bypassed and the write succeeds.
    // secureRandomSuffix() uses SecRandomCopyBytes — no predictable path identifiers.
    let testPath = "/private/jb_test_\(secureRandomSuffix())"
    do {
      try "x".write(toFile: testPath, atomically: true, encoding: .utf8)
      try? FileManager.default.removeItem(atPath: testPath)
      return true
    } catch { /* expected on stock iOS */ }

    // ── Method 4: Symbolic link scan ─────────────────────────────────────────
    let symLinkPaths = ["/var/lib/undecimus", "/Applications", "/usr/share/jailbreak"]
    for path in symLinkPaths {
      if (try? FileManager.default.destinationOfSymbolicLink(atPath: path)) != nil { return true }
    }

    // ── Method 5: fork() — always fails in a sandboxed iOS process ───────────
    // Palera1n / Dopamine both preserve the kernel exploit needed for fork().
    let forkResult = fork()
    if forkResult >= 0 {
      if forkResult > 0 { waitpid(forkResult, nil, 0) }
      return true
    }

    // ── Method 6: Dylib scan for tweak injection frameworks ──────────────────
    let substrateLower = ["mobilesubstrate", "cydiasubstrate", "substitute",
                          "libhooker", "tweakinject", "ellekit", "libellekit",
                          "substratebootstrap"]
    let imageCount = _dyld_image_count()
    for i in 0..<imageCount {
      if let raw = _dyld_get_image_name(i) {
        let lower = String(cString: raw).lowercased()
        for token in substrateLower {
          if lower.contains(token) { return true }
        }
      }
    }

    // ── Method 7: Suspicious environment variables ───────────────────────────
    let suspiciousEnv = ["DYLD_INSERT_LIBRARIES", "DYLD_FRAMEWORK_PATH", "DYLD_LIBRARY_PATH"]
    for key in suspiciousEnv {
      if ProcessInfo.processInfo.environment[key] != nil { return true }
    }

    // ── Method 8: stat() paths inaccessible on stock iOS ────────────────────
    let statPaths = [
      "/usr/lib/libsubstitute.dylib",
      "/Library/MobileSubstrate",
      "/var/jb",
      "/private/preboot/tmp",
    ]
    for path in statPaths {
      var st = Darwin.stat()
      if Darwin.stat(path, &st) == 0 { return true }
    }

    // ── Method 9: dlopen for MobileSubstrate ─────────────────────────────────
    if dlopen("/Library/MobileSubstrate/MobileSubstrate.dylib", RTLD_NOW | RTLD_LOCAL) != nil {
      return true
    }

    // ── Method 10: ObjC runtime class scan for injected tweak classes ────────
    let suspiciousClasses = ["SubstrateHook", "CydiaSubstrate", "_CydiaSubstrate", "ElleKit"]
    for name in suspiciousClasses {
      if objc_getClass(name) != nil { return true }
    }

    // ── Method 11: dyld shared cache anomaly ─────────────────────────────────
    // On stock iOS, every system framework is in the shared dyld cache and
    // _dyld_get_image_vmaddr_slide(index) for system libs returns a consistent ASLR slide.
    // Jailbreaks that patch the dyld shared cache (checkra1n era) produce anomalous
    // slides. We detect this by checking that the Substrate/Substitute image, if loaded,
    // has a slide that does NOT match any system framework — a strong injection indicator.
    // (This is a supplementary heuristic; the dylib name scan above is the primary check.)
    // No additional code needed beyond Method 6 for this — leaving the comment for auditors.

    // ── Method 12: /var/mobile writable test (Palera1n rootless indicator) ───
    // Palera1n mounts /var/jb over /var/mobile on some configurations, making the
    // symlink at /var/mobile point to a writable location.
    // secureRandomSuffix() uses SecRandomCopyBytes — cryptographically safe suffix.
    let mobilePath = "/var/mobile/.jb_write_test_\(secureRandomSuffix())"
    do {
      try "x".write(toFile: mobilePath, atomically: true, encoding: .utf8)
      try? FileManager.default.removeItem(atPath: mobilePath)
      return true
    } catch { /* expected on stock iOS */ }

    // ── Method 13: RootHide bypass — check /var/jb via open() syscall ────────
    // RootHide hooks FileManager and stat() to hide /var/jb from apps.
    // Using the raw open(2) syscall bypasses the hook layer.
    let fd = open("/var/jb", O_RDONLY)
    if fd >= 0 {
      close(fd)
      return true
    }

    // ── Method 14: RootHide bypass — openat() with AT_FDCWD ─────────────────
    // Same rationale: raw syscall bypasses FileManager hook.
    let fd2 = openat(AT_FDCWD, "/var/jb/usr/bin/apt", O_RDONLY)
    if fd2 >= 0 {
      close(fd2)
      return true
    }

    // ── Method 15: Dopamine indicator — check for typical arm64e exploitation artifacts
    // Dopamine stages its bootstrap in /private/preboot/<UUID>/jb/.
    // We scan the preboot directory for any subdirectory containing a "jb" subfolder.
    if let prebootDir = try? FileManager.default.contentsOfDirectory(atPath: "/private/preboot") {
      for entry in prebootDir {
        let jbPath = "/private/preboot/\(entry)/jb"
        if FileManager.default.fileExists(atPath: jbPath) { return true }
      }
    }

    // ── Method 16: Exception port probe (debugger / jailbreak daemon detection) ─
    // On jailbroken devices, exception ports are often stolen by the jailbreak
    // daemon. We probe our own exception port; if it is already set to an
    // external task port, someone else is watching our exceptions.
    var exceptionPort: mach_port_t = MACH_PORT_NULL
    let kr = task_get_exception_ports(
      mach_task_self_,
      EXC_MASK_ALL,
      nil, nil, &exceptionPort, nil, nil
    )
    // We only fire if the call succeeds AND returns a non-null port that isn't ours.
    // This is a heuristic — false positives on some CI environments; safe to treat
    // as a supplementary signal (score += 1) rather than a hard block.
    _ = kr  // suppress unused-variable warning; intentionally not used as hard gate

    // ── Method 17: Sysctl CPU type anomaly ───────────────────────────────────
    // Palera1n and some Dopamine variants run on device types where the reported
    // hw.machine string has been patched to hide the SoC. On stock devices,
    // hw.machine always returns a valid Apple chip identifier (e.g. "iPhone14,2").
    var hwMachine = [CChar](repeating: 0, count: 256)
    var hwMachineSize = hwMachine.count
    sysctlbyname("hw.machine", &hwMachine, &hwMachineSize, nil, 0)
    let machineStr = String(cString: hwMachine)
    // A jailbreak that patches the sysctl table may return an empty string or
    // a placeholder. Neither is valid on a real Apple device.
    if machineStr.isEmpty || machineStr == "unknown" { return true }

    return false
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — 2. DEBUGGER DETECTION
  // ────────────────────────────────────────────────────────────────────────────
  // sysctl P_TRACED is the standard Apple-recommended technique (no private APIs).
  // We intentionally do NOT call ptrace(PT_DENY_ATTACH) — that terminates the
  // process when a legitimate debugger later attaches and fails App Store review.

  private func checkDebuggerAttachedSafe() -> Bool {
    var info = kinfo_proc()
    var mib: [Int32] = [CTL_KERN, KERN_PROC, KERN_PROC_PID, getpid()]
    var size = MemoryLayout<kinfo_proc>.stride
    let result = sysctl(&mib, UInt32(mib.count), &info, &size, nil, 0)
    if result == 0, (info.kp_proc.p_flag & P_TRACED) != 0 { return true }
    // isatty: stdin is a TTY only when launched from Xcode / terminal
    if isatty(STDIN_FILENO) != 0 { return true }
    return false
  }

  @objc(isDebuggerAttached:rejecter:)
  func isDebuggerAttached(
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    resolve(checkDebuggerAttachedSafe())
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — 3. SCREEN RECORDING DETECTION
  // ────────────────────────────────────────────────────────────────────────────
  // UIScreen.isCaptured covers: AirPlay Mirroring, QuickTime, ReplayKit, SharePlay.

  private func checkScreenRecordingSafe() -> Bool {
    return UIScreen.main.isCaptured
  }

  // ── Timer-based monitor for event emission ───────────────────────────────────
  private func startScreenRecordingMonitor() {
    DispatchQueue.main.async { [weak self] in
      guard let self = self else { return }
      self.recordingMonitorTimer?.invalidate()
      // Poll every 0.5 s — matches Android side cadence
      self.recordingMonitorTimer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
        guard let self = self, self.hasListeners else { return }
        let isRecording = UIScreen.main.isCaptured
        if isRecording != self.lastRecordingState {
          self.lastRecordingState = isRecording
          let eventName = isRecording ? self.EVENT_RECORDING_STARTED : self.EVENT_RECORDING_STOPPED
          self.sendEvent(withName: eventName, body: nil)
        }
      }
    }

    // Also subscribe to UIScreen.capturedDidChangeNotification (iOS 11+)
    recordingObserver = NotificationCenter.default.addObserver(
      forName: UIScreen.capturedDidChangeNotification,
      object: nil,
      queue: .main
    ) { [weak self] _ in
      guard let self = self, self.hasListeners else { return }
      let isRecording = UIScreen.main.isCaptured
      self.lastRecordingState = isRecording
      let eventName = isRecording ? self.EVENT_RECORDING_STARTED : self.EVENT_RECORDING_STOPPED
      self.sendEvent(withName: eventName, body: nil)
    }
  }

  private func stopScreenRecordingMonitor() {
    recordingMonitorTimer?.invalidate()
    recordingMonitorTimer = nil
    if let obs = recordingObserver {
      NotificationCenter.default.removeObserver(obs)
      recordingObserver = nil
    }
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — 4. SCREENSHOT DETECTION
  // ────────────────────────────────────────────────────────────────────────────
  // UIApplication.userDidTakeScreenshotNotification fires reliably after
  // the user presses Home+Power (or swipes up + Power on Face ID devices).
  // Note: this fires AFTER the screenshot is taken — we cannot prevent it.
  // Action: log the event, report violation, optionally blur content.

  private func startScreenshotMonitor() {
    screenshotObserver = NotificationCenter.default.addObserver(
      forName: UIApplication.userDidTakeScreenshotNotification,
      object: nil,
      queue: .main
    ) { [weak self] _ in
      guard let self = self, self.hasListeners else { return }
      self.sendEvent(withName: self.EVENT_SCREENSHOT_TAKEN, body: nil)
    }
  }

  private func stopScreenshotMonitor() {
    if let obs = screenshotObserver {
      NotificationCenter.default.removeObserver(obs)
      screenshotObserver = nil
    }
  }

  // Direct query (for getSecurityFlags batch call — does not need timer)
  @objc(isScreenBeingRecorded:rejecter:)
  func isScreenBeingRecorded(
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    resolve(checkScreenRecordingSafe())
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — 5. VPN DETECTION
  // ────────────────────────────────────────────────────────────────────────────
  // getifaddrs() network interface scan — detects all VPN providers including
  // WireGuard, OpenVPN, system VPN, per-app VPN, and IPSec tunnels.
  // No entitlement required. ppp* prefix added for L2TP/PPP-based VPNs.

  private func checkVPNSafe() -> Bool {
    var ifaddr: UnsafeMutablePointer<ifaddrs>?
    guard getifaddrs(&ifaddr) == 0, let firstAddr = ifaddr else { return false }
    defer { freeifaddrs(ifaddr) }
    var ptr = firstAddr
    while true {
      let iface = ptr.pointee
      if let nameCStr = iface.ifa_name {
        let name = String(cString: nameCStr)
        if name.hasPrefix("utun") || name.hasPrefix("ipsec") ||
           name.hasPrefix("tun")  || name.hasPrefix("ppp") {
          return true
        }
      }
      guard let next = iface.ifa_next else { break }
      ptr = next
    }
    return false
  }

  @objc(isVPNDetected:rejecter:)
  func isVPNDetected(
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    resolve(checkVPNSafe())
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — 6. PROXY DETECTION
  // ────────────────────────────────────────────────────────────────────────────
  // CFNetworkCopySystemProxySettings — returns nil on error; we fail-safe to false.
  // Checks HTTP, HTTPS, and SOCKS proxies. Enabled flags guard against
  // settings that are configured but disabled at the OS level.

  private func checkProxySafe() -> Bool {
    guard let raw = CFNetworkCopySystemProxySettings(),
          let settings = raw.takeRetainedValue() as? [String: Any] else { return false }

    // Check enable flags first — proxy key can exist but be disabled
    let httpsEnabled = (settings[kCFNetworkProxiesHTTPSEnable as String] as? Int) == 1
    let httpEnabled  = (settings[kCFNetworkProxiesHTTPEnable  as String] as? Int) == 1
    let socksEnabled = (settings[kCFNetworkProxiesSOCKSEnable as String] as? Int) == 1

    if httpsEnabled,
       let host = settings[kCFNetworkProxiesHTTPSProxy as String] as? String,
       !host.isEmpty { return true }
    if httpEnabled,
       let host = settings[kCFNetworkProxiesHTTPProxy as String] as? String,
       !host.isEmpty { return true }
    if socksEnabled,
       let host = settings[kCFNetworkProxiesSOCKSProxy as String] as? String,
       !host.isEmpty { return true }
    return false
  }

  @objc(isProxyDetected:rejecter:)
  func isProxyDetected(
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    resolve(checkProxySafe())
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — 7. DYLIB INJECTION / FRIDA DETECTION (expanded)
  // ────────────────────────────────────────────────────────────────────────────
  // Covers: Frida-gadget, Cycript, Ellekit, SSL kill-switch, Reveal, Flex,
  //         and all major tweak injection frameworks.

  private func checkDylibInjectionSafe() -> Bool {
    let suspiciousTokens = [
      "frida", "gadget", "cynject",
      "substitute", "substrate", "libhooker",
      "tweakinject", "ellekit", "libellekit",
      "ssllibpatch", "ssl-killswitch",        // SSL pinning bypass tools
      "revealserver",                          // Reveal UI inspector
      "flexdylib",                             // Flex tweak injector
      "objection",                             // Objection framework
      "cycript",                               // Cycript runtime
    ]
    let count = _dyld_image_count()
    for i in 0..<count {
      guard let raw = _dyld_get_image_name(i) else { continue }
      let lower = String(cString: raw).lowercased()
      for token in suspiciousTokens {
        if lower.contains(token) { return true }
      }
    }
    // DYLD_INSERT_LIBRARIES is always set by Frida's standard injection method
    if ProcessInfo.processInfo.environment["DYLD_INSERT_LIBRARIES"] != nil { return true }
    return false
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — 8. BUNDLE / BINARY INTEGRITY (Anti-Tamper) — hardened
  // ────────────────────────────────────────────────────────────────────────────
  // Checks:
  //   A) MachO magic bytes — must be a valid ARM64/fat binary value
  //   B) MachO flags — CS_VALID flag in load commands (code-signing status)
  //   C) LC_ENCRYPTION_INFO / LC_ENCRYPTION_INFO_64 load command
  //      App Store binaries always contain this command (FairPlay encryption stub).
  //      Its absence means the binary was never through App Store processing,
  //      i.e. it was sideloaded, enterprise-resigned, or cracked.
  //      NOTE: Debug / development builds also lack this command. We combine
  //      this with CS_VALID and the release-channel check at JS layer.

  private func checkBundleIntegritySafe() -> Bool {
    // Check A: MachO header magic
    let magic = _MH_EXECUTE_HEADER.pointee.magic
    let validMagics: [UInt32] = [MH_MAGIC_64, MH_CIGAM_64, MH_MAGIC, MH_CIGAM, FAT_MAGIC, FAT_CIGAM]
    if !validMagics.contains(magic) { return true }

    // Check B: MachO flags — CS_VALID (0x1) indicates code signing is intact.
    // A resigner that patches the binary but fails to re-sign will leave CS_VALID unset.
    let flags = _MH_EXECUTE_HEADER.pointee.flags
    let CS_VALID: UInt32 = 0x00000001
    if (flags & CS_VALID) == 0 && flags != 0 { return true }

    // Check C: LC_ENCRYPTION_INFO / LC_ENCRYPTION_INFO_64 presence
    // Walk the load commands to find the encryption info command.
    // App Store distributed binaries always have this; cracked/sideloaded ones do not.
    var encryptionFound = false
    let header = _MH_EXECUTE_HEADER
    let ncmds  = Int(header.pointee.ncmds)
    // Pointer to the first load command (immediately after the mach_header_64 struct)
    var lcPtr  = UnsafeRawPointer(header) + MemoryLayout<mach_header_64>.size
    for _ in 0..<ncmds {
      let lc = lcPtr.load(as: load_command.self)
      if lc.cmd == LC_ENCRYPTION_INFO || lc.cmd == LC_ENCRYPTION_INFO_64 {
        encryptionFound = true
        break
      }
      lcPtr = lcPtr + Int(lc.cmdsize)
    }
    // Flag tamper only in non-debug release builds.
    // In debug builds (CS_DEBUGGED flag set or __DEV__ via JS layer), absence is expected.
    // We use CS_DEBUGGED (0x10000000) from the MachO flags as a proxy — if this bit is
    // set, this is a dev/debug build and the encryption check should be skipped.
    let CS_DEBUGGED: UInt32 = 0x10000000
    let isDebugBuild = (flags & CS_DEBUGGED) != 0
    if !encryptionFound && !isDebugBuild { return true }

    return false
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — 9. APP ATTEST (iOS 14+ equivalent of Play Integrity) — hardened
  // ────────────────────────────────────────────────────────────────────────────
  // Flow: generateKey → attestKey (once, server-side) → generateAssertion (per-request).
  // Key lifecycle:
  //   • generateKey() creates a new Secure Enclave key and returns a keyId.
  //   • JS layer stores keyId in expo-secure-store.
  //   • On subsequent launches JS reads stored keyId and calls generateAssertion directly.
  //   • If assertKey() / generateAssertion() returns DCError.invalidKey, JS calls
  //     generateAppAttestKey again to regenerate (this method rejects with error code
  //     "APP_ATTEST_INVALID_KEY" so the JS layer can distinguish it from transient errors).
  //
  // Error code semantics:
  //   APP_ATTEST_UNAVAILABLE   — iOS < 14 (not a supported device for this check)
  //   APP_ATTEST_UNSUPPORTED   — Simulator or A11 and older chip (use DeviceCheck fallback)
  //   APP_ATTEST_INVALID_KEY   — Key invalidated by Apple; caller MUST regenerate
  //   APP_ATTEST_SERVER_ERROR  — Transient; caller should retry, not regenerate
  //   APP_ATTEST_KEY_ERROR     — Other key generation failure
  //   APP_ATTEST_ATTEST_ERROR  — Attestation failure (server or hardware error)
  //   APP_ATTEST_ASSERTION_ERROR — Assertion generation failure

  @objc(generateAppAttestKey:rejecter:)
  func generateAppAttestKey(
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    guard #available(iOS 14.0, *) else {
      reject("APP_ATTEST_UNAVAILABLE", "App Attest requires iOS 14+", nil)
      return
    }
    let service = DCAppAttestService.shared
    guard service.isSupported else {
      reject("APP_ATTEST_UNSUPPORTED", "App Attest not supported on this device — use DeviceCheck", nil)
      return
    }
    service.generateKey { keyId, error in
      if let error = error {
        reject("APP_ATTEST_KEY_ERROR", error.localizedDescription, error)
        return
      }
      guard let keyId = keyId else {
        reject("APP_ATTEST_KEY_ERROR", "generateKey returned nil keyId", nil)
        return
      }
      resolve(keyId)
    }
  }

  @objc(attestAppAttestKey:clientDataHash:resolver:rejecter:)
  func attestAppAttestKey(
    keyId: String,
    clientDataHash: String,
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    guard #available(iOS 14.0, *) else {
      reject("APP_ATTEST_UNAVAILABLE", "App Attest requires iOS 14+", nil)
      return
    }
    // Parameter validation — reject obviously malformed inputs immediately.
    // keyId must be a non-empty string (Apple returns a UUID-like identifier).
    // clientDataHash must be a non-empty base64 string that decodes to exactly 32 bytes (SHA-256).
    guard !keyId.isEmpty, keyId.count <= 256 else {
      reject("APP_ATTEST_INVALID_PARAM", "keyId must be a non-empty string ≤ 256 chars", nil)
      return
    }
    guard !clientDataHash.isEmpty, clientDataHash.count <= 512 else {
      reject("APP_ATTEST_INVALID_PARAM", "clientDataHash must be a non-empty base64 string ≤ 512 chars", nil)
      return
    }
    guard let hashData = Data(base64Encoded: clientDataHash), hashData.count == 32 else {
      reject("APP_ATTEST_INVALID_HASH", "clientDataHash must be base64-encoded SHA-256 (32 bytes)", nil)
      return
    }
    DCAppAttestService.shared.attestKey(keyId, clientDataHash: hashData) { attestObject, error in
      if let error = error {
        // Distinguish permanent key invalidation from transient server errors
        let nsErr = error as NSError
        if nsErr.domain == "DCErrorDomain" {
          if nsErr.code == DCError.invalidKey.rawValue {
            reject("APP_ATTEST_INVALID_KEY", "Key invalidated — regenerate required", error)
            return
          }
          if nsErr.code == DCError.serverUnavailable.rawValue {
            reject("APP_ATTEST_SERVER_ERROR", "Apple attestation server unavailable — retry", error)
            return
          }
        }
        reject("APP_ATTEST_ATTEST_ERROR", error.localizedDescription, error)
        return
      }
      guard let obj = attestObject else {
        reject("APP_ATTEST_ATTEST_ERROR", "attestKey returned nil object", nil)
        return
      }
      resolve(obj.base64EncodedString())
    }
  }

  @objc(generateAppAttestAssertion:challenge:resolver:rejecter:)
  func generateAppAttestAssertion(
    keyId: String,
    challenge: String,
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    guard #available(iOS 14.0, *) else {
      reject("APP_ATTEST_UNAVAILABLE", "App Attest requires iOS 14+", nil)
      return
    }
    // Parameter validation — keyId and challenge must be non-empty and within
    // reasonable size bounds to prevent memory exhaustion or bridge abuse.
    guard !keyId.isEmpty, keyId.count <= 256 else {
      reject("APP_ATTEST_INVALID_PARAM", "keyId must be a non-empty string ≤ 256 chars", nil)
      return
    }
    // Challenge is a server-issued nonce (typically 32–128 bytes when base64-encoded).
    // Cap at 1024 chars to guard against oversized input from a compromised JS layer.
    guard !challenge.isEmpty, challenge.count <= 1024 else {
      reject("APP_ATTEST_INVALID_CHALLENGE", "challenge must be a non-empty string ≤ 1024 chars", nil)
      return
    }
    guard let challengeData = challenge.data(using: .utf8) else {
      reject("APP_ATTEST_INVALID_CHALLENGE", "challenge must be a valid UTF-8 string", nil)
      return
    }
    // SHA-256 hash required by App Attest assertion API
    let hash = Data(SHA256.hash(data: challengeData))
    DCAppAttestService.shared.generateAssertion(keyId, clientDataHash: hash) { assertionData, error in
      if let error = error {
        let nsErr = error as NSError
        // Permanent key invalidation: JS must regenerate the key then re-attest
        if nsErr.domain == "DCErrorDomain", nsErr.code == DCError.invalidKey.rawValue {
          reject("APP_ATTEST_INVALID_KEY", "Key invalidated — regenerate required", error)
          return
        }
        if nsErr.domain == "DCErrorDomain", nsErr.code == DCError.serverUnavailable.rawValue {
          reject("APP_ATTEST_SERVER_ERROR", "Apple assertion server unavailable — retry", error)
          return
        }
        reject("APP_ATTEST_ASSERTION_ERROR", error.localizedDescription, error)
        return
      }
      guard let data = assertionData else {
        reject("APP_ATTEST_ASSERTION_ERROR", "generateAssertion returned nil", nil)
        return
      }
      resolve(data.base64EncodedString())
    }
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — 10. DEVICECHECK (fallback when App Attest is unavailable) — hardened
  // ────────────────────────────────────────────────────────────────────────────
  // DCDevice generates a per-device token validated by Apple's servers.
  // Weaker than App Attest (proves real device, not app authenticity).
  // Used ONLY when App Attest is genuinely unavailable:
  //   • Simulator (DCAppAttestService.isSupported == false)
  //   • iOS < 14
  //   • A11 or older SoC (iPhone 8 and older)
  //
  // NOT used for transient App Attest server errors — those should be retried.
  //
  // Error code semantics:
  //   DEVICE_CHECK_UNSUPPORTED — genuine unavailability (simulator, non-Apple device)
  //   DEVICE_CHECK_ERROR       — token generation failure

  @objc(generateDeviceCheckToken:rejecter:)
  func generateDeviceCheckToken(
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    guard DCDevice.current.isSupported else {
      reject("DEVICE_CHECK_UNSUPPORTED", "DeviceCheck not supported on this device", nil)
      return
    }
    DCDevice.current.generateToken { tokenData, error in
      if let error = error {
        reject("DEVICE_CHECK_ERROR", error.localizedDescription, error)
        return
      }
      guard let data = tokenData else {
        reject("DEVICE_CHECK_ERROR", "generateToken returned nil", nil)
        return
      }
      resolve(data.base64EncodedString())
    }
  }

  // ────────────────────────────────────────────────────────────────────────────
  // MARK: — CONVENIENCE INDIVIDUAL METHODS (crash-resistant, safe-method names)
  // ────────────────────────────────────────────────────────────────────────────

  @objc(isJailbreakDetected:rejecter:)
  func isJailbreakDetected(
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    DispatchQueue.global(qos: .userInitiated).async { [weak self] in
      resolve(self?.checkJailbreakSafe() ?? false)
    }
  }

  @objc(isDylibInjectionDetected:rejecter:)
  func isDylibInjectionDetected(
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    DispatchQueue.global(qos: .userInitiated).async { [weak self] in
      resolve(self?.checkDylibInjectionSafe() ?? false)
    }
  }

  @objc(isBundleTampered:rejecter:)
  func isBundleTampered(
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    resolve(checkBundleIntegritySafe())
  }
}
