// CommonJS — Expo config plugins are require()d by the prebuild pipeline.
// plugins/ is excluded from oxlint via .eslintignore.
const fs   = require('fs');
const path = require('path');
// Resolve @expo/config-plugins from expo's own package tree so we always get
// the SDK-55-compatible version (55.x), not any top-level project dep.
const expoRoot = path.dirname(require.resolve('expo/package.json'));
const { withDangerousMod, withAppBuildGradle } = require(
  require.resolve('@expo/config-plugins', { paths: [expoRoot] })
);

// ─── ProGuard / R8 rules ─────────────────────────────────────────────────────
//
// Goals:
//   - Full R8 code shrinking + obfuscation in release
//   - Remove debug symbols, SourceFile attributes, line number tables
//   - Rename classes / methods / fields aggressively
//   - Keep only what reflection genuinely needs (RN bridge, Kotlin internals)
//   - Resource shrinking (gradle-level, enabled in build.gradle)

const PROGUARD_RULES = `
##──────────────────────────────────────────────────────────────────────────────
## MedAcademy — Release ProGuard / R8 Rules
## Generated by withProguardRules config plugin.
## Managed build — do NOT edit android/app/proguard-rules.pro directly;
## edit this plugin instead.
##──────────────────────────────────────────────────────────────────────────────

# ── General R8 optimizations ──────────────────────────────────────────────────
-optimizations !code/simplification/arithmetic,!code/simplification/cast,!field/*,!class/merging/*
-optimizationpasses 7
-allowaccessmodification
-repackageclasses 'a'   # flatten all packages into single short package name

# Remove all debug information
-renamesourcefileattribute SourceFile
-keepattributes *Annotation*
# Remove line numbers from stack traces (prevents reverse-engineering)
# Remove SourceFile attribute, keep only Exceptions + Signature for reflection
-keepattributes Exceptions,InnerClasses,Signature,EnclosingMethod

# ── React Native — keep bridge infrastructure ─────────────────────────────────
-keep class com.facebook.react.** { *; }
-keep class com.facebook.hermes.** { *; }
-keep class com.facebook.jni.** { *; }
-keep class com.swmansion.reanimated.** { *; }

# ── Our SecurityModule — must survive reflection calls from RN bridge ─────────
-keep class com.medacademy.security.** { *; }

# ── Our UploadBridge / ForegroundUploadService — must survive reflection + RN bridge ──
-keep class com.medacademy.upload.** { *; }

# ── Expo / React Native modules that use reflection ──────────────────────────
-keep class expo.modules.** { *; }
-keep class com.google.android.** { *; }

# ── PHP API / OkHttp / Ktor — keep network classes ─────────────────────────
-keep class okhttp3.** { *; }
-keep class okio.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**
-dontwarn okio.**

# ── Google Play Integrity API (accessed via reflection in SecurityModule) ──────
-keep class com.google.android.play.core.integrity.** { *; }
-dontwarn com.google.android.play.core.**

# ── Kotlin coroutines / stdlib ────────────────────────────────────────────────
-keep class kotlin.** { *; }
-keep class kotlinx.** { *; }
-dontwarn kotlin.**
-dontwarn kotlinx.**

# ── VdoCipher SDK ─────────────────────────────────────────────────────────────
-keep class com.vdocipher.** { *; }
-dontwarn com.vdocipher.**

# ── Hermes JS engine ──────────────────────────────────────────────────────────
-keep class com.facebook.hermes.unicode.** { *; }
-keep class com.facebook.jni.** { *; }

# ── Remove logging in release ─────────────────────────────────────────────────
-assumenosideeffects class android.util.Log {
    public static int v(...);
    public static int d(...);
    public static int i(...);
    public static int w(...);
    public static int e(...);
    public static int wtf(...);
}

# ── Prevent stripping of classes needed by expo-modules ──────────────────────
-keep @interface expo.modules.core.interfaces.DoNotStrip
-keep @expo.modules.core.interfaces.DoNotStrip class *
-keepclassmembers class * {
    @expo.modules.core.interfaces.DoNotStrip *;
}

# ── Suppress warnings for optional dependencies ───────────────────────────────
-dontwarn com.facebook.react.turbomodule.**
-dontwarn com.facebook.react.fabric.**
-dontwarn edu.umd.cs.findbugs.**
-dontwarn javax.annotation.**
`;

// ─── withDangerousMod: write proguard-rules.pro ──────────────────────────────

function withProguardRulesFile(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const proguardPath = path.join(
        cfg.modRequest.projectRoot, 'android', 'app', 'proguard-rules.pro'
      );
      fs.writeFileSync(proguardPath, PROGUARD_RULES.trimStart(), 'utf8');
      return cfg;
    },
  ]);
}

// ─── withAppBuildGradle: enable R8 + resource shrinking in release ────────────

function withR8Enabled(config) {
  return withAppBuildGradle(config, (cfg) => {
    let contents = cfg.modResults.contents;

    // Enable minifyEnabled + shrinkResources + proguard in the release buildType.
    // The Expo-generated build.gradle has a release block we can target.
    // Idempotent: only patch if not already set.
    if (!contents.includes('minifyEnabled true')) {
      contents = contents.replace(
        /release\s*\{([^}]*)\}/s,
        (match, inner) => {
          let patched = inner;
          if (!patched.includes('minifyEnabled'))    patched += '\n            minifyEnabled true';
          if (!patched.includes('shrinkResources'))  patched += '\n            shrinkResources true';
          if (!patched.includes('proguardFiles')) {
            patched += "\n            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'";
          }
          return `release {${patched}}`;
        }
      );
      cfg.modResults.contents = contents;
    }
    return cfg;
  });
}

// ─── Combined export ──────────────────────────────────────────────────────────

const withProguardRules = (config) => {
  config = withProguardRulesFile(config);
  config = withR8Enabled(config);
  return config;
};

module.exports = withProguardRules;
